// Copyright 2026 AxonFlow
// SPDX-License-Identifier: BUSL-1.1

package capability

import (
	"encoding/json"
	"os"
	"path/filepath"
	"testing"
)

// frozen is one entry of the pre-#3618 served list, in the wire's own field
// names.
type frozen struct {
	Name        string `json:"name"`
	Since       string `json:"since"`
	Description string `json:"description"`
}

func readFrozen(t *testing.T, plane string) []frozen {
	t.Helper()
	path := filepath.Join("testdata", "health_wire_freeze_"+plane+".json")
	b, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("reading the frozen wire for the %s plane: %v", plane, err)
	}
	var out []frozen
	if err := json.Unmarshal(b, &out); err != nil {
		t.Fatalf("decoding %s: %v", path, err)
	}
	if len(out) == 0 {
		t.Fatalf("%s is empty; every comparison against it would pass vacuously", path)
	}
	return out
}

// TestProjectionReproducesTheFrozenWire is the control on the whole of #3618.
//
// Replacing a hand-maintained literal with a projection is only safe if the
// projection produces the SAME BYTES. /health is a discovery surface: a client
// that stops seeing a capability name reads it as "the platform dropped
// support", and a description that changes is a diff in every customer's
// monitoring. The two testdata files were produced by RUNNING the two planes'
// getCapabilities() before the change, so they are the wire as it actually was
// and not a transcription of it.
//
// This test necessarily fails when a capability is legitimately ADDED, which is
// the point: adding to a wire surface 29 entries' worth of clients branch on
// should require deleting a line that says "this is what we used to serve".
func TestProjectionReproducesTheFrozenWire(t *testing.T) {
	for _, plane := range []string{PlaneAgent, PlaneOrchestrator} {
		t.Run(plane, func(t *testing.T) {
			want := readFrozen(t, plane)
			got := Load().Advertise(plane)
			if len(got) != len(want) {
				t.Fatalf("the %s plane projects %d capabilities, the frozen wire had %d",
					plane, len(got), len(want))
			}
			for i := range want {
				if got[i].Name != want[i].Name {
					t.Errorf("position %d: projected %q, frozen wire had %q. ORDER IS PART OF "+
						"THE WIRE — a client that indexes the array sees a different capability",
						i, got[i].Name, want[i].Name)
					continue
				}
				if got[i].Since != want[i].Since {
					t.Errorf("%s: projected since %q, frozen wire had %q",
						got[i].Name, got[i].Since, want[i].Since)
				}
				if got[i].Description != want[i].Description {
					t.Errorf("%s: the description changed.\n  projected: %q\n  frozen:    %q",
						got[i].Name, got[i].Description, want[i].Description)
				}
			}
		})
	}
}

// TestTheFrozenWireIsNotVacuous proves the comparison above has something to
// compare. A freeze file that decoded to entries with empty names would make
// every assertion in the loop pass against a projection of empty names.
func TestTheFrozenWireIsNotVacuous(t *testing.T) {
	agent := readFrozen(t, PlaneAgent)
	orch := readFrozen(t, PlaneOrchestrator)
	if len(agent) < 20 || len(orch) < 10 {
		t.Fatalf("the frozen wire is implausibly small (agent %d, orchestrator %d); it was "+
			"captured from a build where getCapabilities() returned almost nothing",
			len(agent), len(orch))
	}
	for _, plane := range [][]frozen{agent, orch} {
		for i, f := range plane {
			if f.Name == "" || f.Since == "" || f.Description == "" {
				t.Fatalf("frozen entry %d has an empty field: %+v", i, f)
			}
		}
	}
	// A positive control on the CONTENT, not just the shape: the freeze must
	// contain the entry #3618 was filed about, or it was captured from the
	// wrong tree.
	var found bool
	for _, f := range agent {
		if f.Name == "authzen_evaluation" {
			found = true
		}
	}
	if !found {
		t.Fatalf("the frozen agent wire has no authzen_evaluation entry, so it was not " +
			"captured from a tree that had it")
	}
}

// TestTheOrchestratorListIsAnOrderedSubsetOfTheAgentList pins the invariant the
// two hand-maintained literals used to hold by convention.
//
// It is a second, independent witness to the freeze files. Those files could in
// principle be regenerated by the same edit that broke the projection; this
// property could not be satisfied that way, because it relates the two planes
// to each other rather than either of them to a recorded past.
func TestTheOrchestratorListIsAnOrderedSubsetOfTheAgentList(t *testing.T) {
	agent := Load().Advertise(PlaneAgent)
	orch := Load().Advertise(PlaneOrchestrator)
	if len(orch) == 0 || len(agent) == 0 {
		t.Fatal("a plane projects nothing, so the subset relation below is vacuous")
	}
	if len(orch) >= len(agent) {
		t.Fatalf("the orchestrator projects %d capabilities and the agent %d; the "+
			"orchestrator list is documented as a deliberate SUBSET", len(orch), len(agent))
	}
	agentAt := map[string]int{}
	agentSince := map[string]string{}
	for i, a := range agent {
		agentAt[a.Name] = i
		agentSince[a.Name] = a.Since
	}
	prev := -1
	for _, o := range orch {
		at, ok := agentAt[o.Name]
		if !ok {
			t.Errorf("the orchestrator advertises %q, which the agent does not. The "+
				"orchestrator serves a subset of the agent's surface, so a name here and "+
				"not there is a capability one plane invented", o.Name)
			continue
		}
		if at <= prev {
			t.Errorf("%q appears out of the agent's order; a client that merges the two "+
				"lists positionally would misalign them", o.Name)
		}
		prev = at
		if agentSince[o.Name] != o.Since {
			t.Errorf("%q is since %q on the orchestrator and %q on the agent. Two literals "+
				"could disagree like this and each look right alone; one registry cannot, "+
				"so this failure means the projection itself is wrong",
				o.Name, o.Since, agentSince[o.Name])
		}
	}
}

// TestEveryHealthEntryIsAdvertisedSomewhere catches an entry that names planes
// nobody projects — a health block that exists in the file and reaches no wire.
func TestEveryHealthEntryIsAdvertisedSomewhere(t *testing.T) {
	served := map[string]bool{}
	for _, plane := range []string{PlaneAgent, PlaneOrchestrator} {
		for _, a := range Load().Advertise(plane) {
			served[a.Name] = true
		}
	}
	for _, e := range Load().Entries {
		if e.Health == nil {
			continue
		}
		if !served[e.Health.Name] {
			t.Errorf("%s declares a health block for %q that no plane serves",
				e.ID, e.Health.Name)
		}
	}
}

// TestDescriptionOverrideIsAppliedPerPlane proves the one divergence the census
// records is reproduced rather than flattened, in BOTH directions: the
// overriding plane gets the override and the other plane does not.
//
// A one-sided check would pass on a projection that returned the override to
// everybody, which is the failure that would silently rewrite the agent's wire.
func TestDescriptionOverrideIsAppliedPerPlane(t *testing.T) {
	var checked int
	for _, e := range Load().Entries {
		if e.Health == nil || len(e.Health.DescriptionOverrides) == 0 {
			continue
		}
		for plane, want := range e.Health.DescriptionOverrides {
			checked++
			var gotOverridden, gotBase string
			for _, other := range e.Health.Planes {
				for _, a := range Load().Advertise(other) {
					if a.Name != e.Health.Name {
						continue
					}
					if other == plane {
						gotOverridden = a.Description
					} else {
						gotBase = a.Description
					}
				}
			}
			if gotOverridden != want {
				t.Errorf("%s: plane %q did not receive its override", e.ID, plane)
			}
			if gotBase == "" {
				t.Errorf("%s: no other plane serves %q, so the override cannot be shown to "+
					"be plane-specific", e.ID, e.Health.Name)
			} else if gotBase != e.Health.Description {
				t.Errorf("%s: a plane with no override served %q, want the base description",
					e.ID, gotBase)
			}
		}
	}
	if checked == 0 {
		t.Skip("no entry uses a description override; nothing to prove here")
	}
}
