// Copyright 2025 AxonFlow
// SPDX-License-Identifier: BUSL-1.1
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Package telemetry provides OpenTelemetry-based tracing for AxonFlow
// policy decisions. One decision = one span. The returned W3C trace_id
// is the correlation primitive that PEPs propagate downstream so all
// gateway-layer decisions stitch into one end-to-end trace
// (ADR-056 §"Trace correlation").
//
// The package exposes a single interface, DecisionTracer, with two
// implementations:
//
//   - noopTracer: returned when AXONFLOW_OTEL_ENDPOINT is empty. No
//     network calls, no required infra. This is the Community-tier
//     default — OTel is opt-in.
//   - otlpTracer: returned when AXONFLOW_OTEL_ENDPOINT is set. Exports
//     spans via OTLP/gRPC to a local or remote OTel collector.
//
// Both impls return a W3C-format trace_id (16-byte hex). The id is
// generated by the OTel SDK regardless of export success — span
// emission is fire-and-forget, so callers can always echo it back to
// the PEP.
package telemetry

import "context"

// DecisionEvent is the per-decision payload recorded as an
// OpenTelemetry span. Fields map to span attributes per ADR-056
// §"Trace correlation" and the OTel semantic conventions where
// applicable (org.id, tenant.id follow the OTel "id" attribute
// convention; decision.* are AxonFlow-namespaced).
type DecisionEvent struct {
	// DecisionID identifies this decision (ULID/UUID). Attribute: decision.id
	DecisionID string

	// OrgID is the AxonFlow org identifier. Attribute: org.id
	OrgID string

	// TenantID is the AxonFlow tenant identifier. Attribute: tenant.id
	TenantID string

	// Stage names the decision plane: "llm" | "tool" | "agent".
	// Attribute: decision.stage
	Stage string

	// Verdict is the policy outcome: "allow" | "deny" | "needs_approval".
	// Attribute: decision.verdict
	Verdict string

	// PolicyIDs lists the policies evaluated for this decision.
	// Attribute: decision.policy_ids (joined as a string-slice attribute)
	PolicyIDs []string

	// LatencyMs is the decision-handler latency in milliseconds.
	// Attribute: decision.latency_ms
	LatencyMs int64

	// Reasons lists human-readable reasons attached to the verdict.
	// Attribute: decision.reasons (joined as a string-slice attribute,
	// truncated to keep attribute size under OTel limits)
	Reasons []string

	// Context carries the sanitized, allowlist-filtered request context
	// the PEP attached to the decision (BukuWarung Layer 2: X-AI-Agent /
	// X-Session-ID / X-Leader-Identity, plus the x-bukuwarung-* family).
	// Keys are already canonicalized to lower_snake_case by the caller
	// (canonicalizeRequestContext). Each entry is emitted as a span
	// attribute under the request.context.<key> namespace so SIEM joins
	// against BigQuery Cloud Audit Logs are deterministic. Nil/empty is
	// the common case (most callers attach no context) and emits nothing.
	Context map[string]string

	// ContextTruncated is set by the caller when the request carried more
	// context keys than the cap allows and the surplus was dropped. Surfaced
	// as the request.context.truncated boolean span attribute so an auditor
	// can tell a partial context map from a complete one.
	ContextTruncated bool
}

// DecisionTracer records a decision event and returns the W3C
// trace_id (32-char lowercase hex) for the PEP to propagate.
//
// The returned trace_id is non-empty whenever the tracer is the OTLP
// impl, regardless of whether the collector is reachable: the OTel SDK
// allocates a TraceID synchronously at span start, then dispatches
// export off the request path. The noop impl returns the zero string —
// callers wiring it into a response body should treat "" as "no trace
// available, OTel is disabled" rather than as an error.
type DecisionTracer interface {
	RecordDecision(ctx context.Context, evt DecisionEvent) (traceID string)
}

// reasonsMaxAttrLen caps the combined length of joined reasons before
// truncation. OTLP attribute values default to a 1 MiB ceiling but
// individual collector backends (Jaeger, Tempo) commonly enforce 32
// KiB per attribute. We stay well below that to keep traces searchable
// without losing the head of the reason list.
const reasonsMaxAttrLen = 4096

// maxContextSpanAttrs caps how many request.context.<key> attributes a
// single decision span carries. The caller (canonicalizeRequestContext)
// already enforces the same key cap, but the tracer re-asserts it as a
// defensive boundary: any DecisionEvent that reaches the span layer with
// more keys (e.g. a future caller that bypasses canonicalization) has the
// surplus dropped and request.context.truncated set rather than blowing
// past collector attribute-count limits. Keys are emitted in sorted order
// so the kept subset is deterministic when the cap fires.
const maxContextSpanAttrs = 10
