package pdp

import (
	"fmt"
	"sort"
	"strings"

	"axonflow/platform/decision/contract"
)

// CompilerVersion identifies the compiler that produced a bundle. It is part of
// the bundle provenance, so a decision can name the compiler that generated the
// Rego it was evaluated against, not merely the policy source.
const CompilerVersion = "axonflow-policy-compiler/1"

// HelperPackage is the platform-owned Rego package every generated condition
// calls into.
const HelperPackage = "axonflow.decision.tri"

// BundlePackagePrefix is the package prefix of a generated bundle module. The
// root is appended, so the system and organization roots compile into different
// packages and cannot overwrite each other's rules even if both are loaded into
// one compiler.
const BundlePackagePrefix = "axonflow.decision.bundle"

// BundlePackage returns the generated package name for a root.
func BundlePackage(root Root) string {
	return BundlePackagePrefix + "." + string(root)
}

// Compile renders a typed authoring document as a Rego v1 module.
//
// The compiler owns condition generation; customer-authored raw Rego is not
// available in the first release. That is what makes the tri-state guarantees
// enforceable: generated code cannot dereference an attribute value without
// first inspecting its state, because generated code never dereferences an
// attribute at all. Every leaf is a call into the platform-owned helper package.
func Compile(d *Document) (string, error) {
	if d == nil {
		return "", fmt.Errorf("compile: document is nil")
	}
	if errs := d.Validate(); len(errs) > 0 {
		msgs := make([]string, 0, len(errs))
		for _, e := range errs {
			msgs = append(msgs, e.Error())
		}
		return "", fmt.Errorf("compile: document failed authoring validation:\n  %s", strings.Join(msgs, "\n  "))
	}
	schema := d.AttributeIndex()

	policies := append([]Policy(nil), d.Policies...)
	sort.Slice(policies, func(i, j int) bool { return policies[i].ID < policies[j].ID })

	// policy_result is one complete object rather than a partial object rule.
	// If any generated expression is undefined the whole object is undefined,
	// the sealed result below is undefined with it, and the Go boundary maps
	// that to Indeterminate. A partial rule would silently omit the broken
	// policy and produce a result object that looks complete.
	//
	// It is rendered BEFORE the module header so the header can decide whether
	// the helper import is used. A document with no policies - an organization
	// that has authored none yet, or a plane whose rows all compiled to
	// nothing - generates an empty policy_result, references no `tri.` helper,
	// and an unconditional import then fails STRICT compilation with
	// "rego_compile_error: import data.axonflow.decision.tri unused". That
	// made an empty authority root impossible to activate: the bundle built,
	// signed and verified, and only failed at engine preparation.
	var body strings.Builder
	body.WriteString("policy_result := {\n")
	for _, p := range policies {
		expr, err := compilePolicy(p, schema)
		if err != nil {
			return "", fmt.Errorf("compile: policy %q: %w", p.ID, err)
		}
		fmt.Fprintf(&body, "\t%q: %s,\n", p.ID, expr)
	}
	body.WriteString("}\n\n")

	var b strings.Builder
	fmt.Fprintf(&b, "# Generated by %s. Do not edit.\n", CompilerVersion)
	b.WriteString("#\n")
	b.WriteString("# Every condition below is a call into the platform-owned tri-state helper\n")
	b.WriteString("# package. There is no bare attribute dereference in this file, and the\n")
	b.WriteString("# bundle lint fails the build if one appears.\n")
	fmt.Fprintf(&b, "package %s\n\n", BundlePackage(d.Root))
	// Derived from the generated body rather than from len(policies): the test
	// that matters is whether the import is USED, and deriving it keeps the
	// two in step if a future policy shape ever compiles without a helper call.
	if strings.Contains(body.String(), "tri.") {
		fmt.Fprintf(&b, "import data.%s\n\n", HelperPackage)
	}
	b.WriteString(body.String())

	// authorities and roots are emitted as data so the Go combiner never has
	// to re-derive from the source document which authority a policy carried.
	// A result whose authority map disagrees with the manifest is a defective
	// bundle, which the boundary checks.
	b.WriteString("authorities := {\n")
	for _, p := range policies {
		fmt.Fprintf(&b, "\t%q: %q,\n", p.ID, string(p.Authority))
	}
	b.WriteString("}\n\n")

	fmt.Fprintf(&b, "result := {\n")
	fmt.Fprintf(&b, "\t\"schema_version\": %q,\n", contract.SchemaVersion)
	fmt.Fprintf(&b, "\t\"root\": %q,\n", string(d.Root))
	fmt.Fprintf(&b, "\t\"document_version\": %d,\n", d.Version)
	b.WriteString("\t\"policies\": policy_result,\n")
	b.WriteString("\t\"authorities\": authorities,\n")
	b.WriteString("}\n")
	return b.String(), nil
}

func compilePolicy(p Policy, schema map[string]AttributeSchema) (string, error) {
	scope, err := compileScope(p.Scope, schema)
	if err != nil {
		return "", err
	}
	actions, err := compileActions(p.Actions, schema)
	if err != nil {
		return "", err
	}
	where, err := compileCondition(p.Where, schema)
	if err != nil {
		return "", err
	}
	if p.ResourceScope != nil {
		rs, err := compileCondition(*p.ResourceScope, schema)
		if err != nil {
			return "", err
		}
		where = kAnd(rs, where)
	}
	if p.Unless != nil {
		u, err := compileCondition(*p.Unless, schema)
		if err != nil {
			return "", err
		}
		// A satisfied exception collapses the policy to non-applicable, which
		// is indistinguishable from the policy not existing. An UNKNOWN
		// exception keeps the policy UNKNOWN through k_not and k_and, so an
		// unevaluable exception cannot quietly suppress a constraint.
		where = kAnd(where, fmt.Sprintf("tri.k_not(%s)", u))
	}
	return kAnd(kAnd(scope, actions), where), nil
}

func kAnd(a, b string) string { return fmt.Sprintf("tri.k_and(%s, %s)", a, b) }

func kOr(a, b string) string { return fmt.Sprintf("tri.k_or(%s, %s)", a, b) }

func foldOr(terms []string) string {
	if len(terms) == 0 {
		return "tri.k_false"
	}
	out := terms[0]
	for _, t := range terms[1:] {
		out = kOr(out, t)
	}
	return out
}

func foldAnd(terms []string) string {
	if len(terms) == 0 {
		return "tri.k_true"
	}
	out := terms[0]
	for _, t := range terms[1:] {
		out = kAnd(out, t)
	}
	return out
}

// PrincipalIDPath and PrincipalGroupsPath are the two attributes scope
// resolution reads. They are ordinary tri-state attributes, which is the point:
// an unresolvable group closure makes a group-scoped constraint UNKNOWN through
// the same machinery as any other unavailable attribute, and an authoritative
// empty closure makes it NO_MATCH. Those two cases must not share a code path,
// because a partial closure may be missing the very constraint that binds while
// an empty one from a realm with no group concept is a fact.
const (
	PrincipalIDPath     = "principal.id"
	PrincipalGroupsPath = "principal.groups"
	ActionIDPath        = "action.id"
	ActionTagsPath      = "action.tags"
	// ResourceAncestorsPath is the resolver-materialized containment closure of
	// the resource under decision: the ordered ancestor identifiers a policy
	// tests membership against to express "inside this space".
	//
	// It is declared here beside the other well-known paths rather than in the
	// layer that consumes it, because a well-known path spelled in two places
	// is two spellings, and the one that drifts is the one no compiler reads.
	// The compiler treats it as an ordinary tri-state collection attribute,
	// which is the point: an unresolvable closure makes a containment-scoped
	// constraint UNKNOWN rather than silently inapplicable, and an
	// authoritatively empty one from a realm with no hierarchy is a fact.
	ResourceAncestorsPath = "resource.ancestors"
)

func compileScope(s Scope, schema map[string]AttributeSchema) (string, error) {
	if s.Organization {
		return "tri.k_true", nil
	}
	var terms []string
	for _, p := range s.Principals {
		t, err := compileCondition(Compare(PrincipalIDPath, OpEq, p.String()), schema)
		if err != nil {
			return "", err
		}
		terms = append(terms, t)
	}
	if len(s.Groups) > 0 {
		lits := make([]any, 0, len(s.Groups))
		for _, g := range s.Groups {
			lits = append(lits, g.String())
		}
		t, err := compileCondition(Intersects(PrincipalGroupsPath, lits...), schema)
		if err != nil {
			return "", err
		}
		terms = append(terms, t)
	}
	return foldOr(terms), nil
}

func compileActions(a ActionSelector, schema map[string]AttributeSchema) (string, error) {
	if a.Any {
		return "tri.k_true", nil
	}
	var terms []string
	if len(a.Actions) > 0 {
		var ids []string
		for _, id := range a.Actions {
			t, err := compileCondition(Compare(ActionIDPath, OpEq, id.String()), schema)
			if err != nil {
				return "", err
			}
			ids = append(ids, t)
		}
		terms = append(terms, foldOr(ids))
	}
	if len(a.RequiredTags) > 0 {
		lits := make([]any, 0, len(a.RequiredTags))
		for _, t := range a.RequiredTags {
			lits = append(lits, t)
		}
		t, err := compileCondition(Superset(ActionTagsPath, lits...), schema)
		if err != nil {
			return "", err
		}
		terms = append(terms, t)
	}
	// Named actions AND required tags narrow together. Two selector axes that
	// widen each other would make "this action, but only when it also carries
	// the pii_egress tag" inexpressible.
	return foldAnd(terms), nil
}

func compileCondition(c Condition, schema map[string]AttributeSchema) (string, error) {
	// The helper's "optional" flag is the POLICY's declared absence handling,
	// not the schema's optionality. The schema says absence is possible; only
	// the policy can say what it means, and the authoring validator refuses a
	// condition over an optional attribute that does not say.
	absentIsNoMatch := func(c Condition) string {
		if c.OnAbsent == AbsentIsNoMatch {
			return "true"
		}
		return "false"
	}
	typeOf := func(path string) string {
		if s, ok := schema[path]; ok && s.Type != "" {
			return string(s.Type)
		}
		return string(TypeAny)
	}

	switch c.Kind {
	case CondTrue:
		return "tri.k_true", nil
	case CondCompare:
		lit, err := regoLiteral(c.Literal)
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("tri.cmp(input.attributes, %q, %q, %s, %q, %s)",
			c.Path, string(c.Op), lit, typeOf(c.Path), absentIsNoMatch(c)), nil
	case CondMember:
		lit, err := regoLiteral(c.Literal)
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("tri.member(input.attributes, %q, %s, %s)", c.Path, lit, absentIsNoMatch(c)), nil
	case CondSuperset:
		lits, err := regoLiteral(c.Literals)
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("tri.superset(input.attributes, %q, %s, %s)", c.Path, lits, absentIsNoMatch(c)), nil
	case CondIntersects:
		lits, err := regoLiteral(c.Literals)
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("tri.intersects(input.attributes, %q, %s, %s)", c.Path, lits, absentIsNoMatch(c)), nil
	case CondAttrCompare:
		return fmt.Sprintf("tri.attr_cmp(input.attributes, %q, %q, %q, %q)",
			c.Path, c.RightPath, string(c.Op), typeOf(c.Path)), nil
	case CondAnd:
		terms, err := compileOperands(c.Operands, schema)
		if err != nil {
			return "", err
		}
		return foldAnd(terms), nil
	case CondOr:
		terms, err := compileOperands(c.Operands, schema)
		if err != nil {
			return "", err
		}
		return foldOr(terms), nil
	case CondNot:
		terms, err := compileOperands(c.Operands, schema)
		if err != nil {
			return "", err
		}
		if len(terms) != 1 {
			return "", fmt.Errorf("not requires exactly one operand, got %d", len(terms))
		}
		return fmt.Sprintf("tri.k_not(%s)", terms[0]), nil
	default:
		return "", fmt.Errorf("condition kind %q is not declared", c.Kind)
	}
}

func compileOperands(ops []Condition, schema map[string]AttributeSchema) ([]string, error) {
	out := make([]string, 0, len(ops))
	for _, o := range ops {
		t, err := compileCondition(o, schema)
		if err != nil {
			return nil, err
		}
		out = append(out, t)
	}
	return out, nil
}

// regoLiteral renders a Go value as a Rego term. JSON is used because a Rego
// term for a scalar, array or object is JSON, and because it refuses anything
// that is not representable rather than emitting a Go-formatted value that
// happens to parse.
//
// It goes through contract.ExactJSON rather than encoding/json, and that is a
// correctness requirement rather than a tidiness one. A plain marshal emits the
// literal the way the caller happened to spell it, so a bound written 1e3 and
// the same bound written 1000 compile to DIFFERENT modules and therefore to
// different bundle digests. Two identical policies would then pin as two
// artifacts, a document that round trips through the authoring API would
// recompile to something other than what is being enforced, and a semantic diff
// would report a change where the policy did not change. Canonicalizing the
// number, the key order and the escaping makes the compiler a function of the
// policy rather than of its spelling.
//
// It is the EXACT encoder, not the normalizing one. A generated module is an
// artifact the runtime compiles raw, so two string literals that differ only in
// Unicode composition must stay two literals: they match different values, and
// collapsing them here would make the compiler erase a distinction the
// evaluator observes.
func regoLiteral(v any) (string, error) {
	b, err := contract.ExactJSON(v)
	if err != nil {
		return "", fmt.Errorf("literal %v is not representable as a Rego term: %w", v, err)
	}
	return string(b), nil
}
