// Copyright 2026 AxonFlow
// SPDX-License-Identifier: BUSL-1.1

package orchestrator

import (
	"context"
	"flag"
	"fmt"
	"net/http"
	"os"
	"path/filepath"
	"reflect"
	"sort"
	"strings"
	"testing"
	"time"

	"github.com/prometheus/client_golang/prometheus"

	"axonflow/platform/decision/activation"
	"axonflow/platform/decision/contract"
	"axonflow/platform/shared/anchoredenforcer"
	sharedidentity "axonflow/platform/shared/identity"
)

// THE THREE ORCHESTRATOR SEAMS' ANSWERS, PINNED BEFORE THEY SHARE A
// CLASSIFIER (#4249 row 5674229604).
//
// The route requests, the workflow step gate and the multi-agent checker each
// classify the engine's verdict and answer it in their own terms. A refactor
// that gives them one classifier must change none of those answers, and a
// refactor that "agrees" is indistinguishable from a correct one unless the
// answers were captured before it. So every seam is driven through its entry,
// with an enforcer double answering each verdict shape and the per-plane
// variants, and each answer (the whole value the seam returns, and the change
// it made to axonflow_decision_enforce_decisions_total) is rendered and
// compared with testdata/seam_verdict_pins_4249.golden.
//
// The golden was written from the tree BEFORE the classifier existed, in the
// commit that added this file alone, and is never regenerated by a later
// change: a difference is a finding, never a fix. -update-seam-pins exists
// only for that first commit.

var updateSeamPins = flag.Bool("update-seam-pins", false, "rewrite testdata/seam_verdict_pins_4249.golden (the pin commit only)")

const seamPinGolden = "testdata/seam_verdict_pins_4249.golden"

// pinExpiredAt is an approval expiry long past, so an expired challenge is
// expired whatever the clock reads.
var pinExpiredAt = time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)

func pinDecision(state contract.OperationalState, reason contract.ReasonCode, d contract.Determining) *contract.Decision {
	return &contract.Decision{DecisionID: "dec-pin", State: state, Reason: reason, Determining: d}
}

func pinApproval(expiresAt time.Time) *contract.ApprovalRequirement {
	return &contract.ApprovalRequirement{
		AllOf:     []contract.ApprovalClause{{Quorum: 1, Eligible: []contract.ID{contract.MustParseID(contract.KindGroup, "Group::mars:reviewers")}}},
		ExpiresAt: expiresAt,
	}
}

// seamPinVerdicts are the six shapes (unavailable, refusal, no decision,
// allow, challenge, deny/error), the variants each seam answers differently,
// and a state no seam recognises, which every seam must withhold.
func seamPinVerdicts() []struct {
	name string
	v    anchoredenforcer.Verdict
} {
	refusal := &sharedidentity.Admission{State: sharedidentity.AdmissionDeny, Reason: sharedidentity.ReasonUnknownRealm, Detail: "no realm admits this credential"}
	allow := func() *contract.Decision {
		return pinDecision(contract.StateAllow, contract.ReasonPermitted, contract.Determining{MatchedPermissions: []string{"p-allow"}})
	}
	challenge := func(a *contract.ApprovalRequirement) *contract.Decision {
		d := pinDecision(contract.StateChallenge, contract.ReasonApprovalRequired, contract.Determining{MatchedRequirement: []string{"req-hold"}})
		d.Approval = a
		return d
	}
	return []struct {
		name string
		v    anchoredenforcer.Verdict
	}{
		{"unavailable", anchoredenforcer.Verdict{Unavailable: anchoredenforcer.CauseEvaluation}},
		{"refusal", anchoredenforcer.Verdict{Refusal: refusal}},
		{"no decision", anchoredenforcer.Verdict{}},
		{"allow", anchoredenforcer.Verdict{Decision: allow()}},
		{"challenge", anchoredenforcer.Verdict{Decision: challenge(pinApproval(time.Time{}))}},
		{"challenge with no approval terms", anchoredenforcer.Verdict{Decision: challenge(nil)}},
		{"challenge already expired", anchoredenforcer.Verdict{Decision: challenge(pinApproval(pinExpiredAt))}},
		{"deny", anchoredenforcer.Verdict{Decision: pinDecision(contract.StateDeny, contract.ReasonExplicitConstraint,
			contract.Determining{MatchedConstraints: []string{"c-first", "c-second"}})}},
		{"error on an unknown constraint", anchoredenforcer.Verdict{Decision: pinDecision(contract.StateError, contract.ReasonUnknownConstraint,
			contract.Determining{MatchedConstraints: []string{"c-known"}, Unknown: []contract.UnknownPolicy{{
				PolicyID: "c-unknown", Authority: contract.AuthorityConstraint, Reason: contract.ReasonNotSupplied, Paths: []string{"env.environment"},
			}}})}},
		{"error on an unknown constraint, with its activation", anchoredenforcer.Verdict{
			Act: &activation.Activation{PolicyBundle: "sha256:pin-bundle"},
			Decision: pinDecision(contract.StateError, contract.ReasonUnknownConstraint,
				contract.Determining{MatchedConstraints: []string{"c-known"}, Unknown: []contract.UnknownPolicy{{
					PolicyID: "c-unknown", Authority: contract.AuthorityConstraint, Reason: contract.ReasonNotSupplied, Paths: []string{"env.environment"},
				}}})}},
		{"a state no seam recognises", anchoredenforcer.Verdict{Decision: pinDecision("SOMETHING_NEW", contract.ReasonPermitted,
			contract.Determining{MatchedPermissions: []string{"p-allow"}})}},
		{"unavailable beside a decision", anchoredenforcer.Verdict{Unavailable: anchoredenforcer.CauseEvaluation, Decision: allow()}},
		{"refusal beside a decision", anchoredenforcer.Verdict{Refusal: refusal, Decision: allow()}},
		{"unavailable beside a refusal", anchoredenforcer.Verdict{Unavailable: anchoredenforcer.CauseEvaluation, Refusal: refusal}},
	}
}

// counterSnapshot is every series of the enforcement counter, by label set.
func counterSnapshot(t *testing.T) map[string]float64 {
	t.Helper()
	reg := prometheus.NewPedanticRegistry()
	if err := reg.Register(anchoredenforcer.Decisions); err != nil {
		t.Fatal(err)
	}
	families, err := reg.Gather()
	if err != nil {
		t.Fatal(err)
	}
	out := map[string]float64{}
	for _, f := range families {
		for _, m := range f.GetMetric() {
			var labels []string
			for _, l := range m.GetLabel() {
				labels = append(labels, l.GetName()+"="+l.GetValue())
			}
			sort.Strings(labels)
			out[strings.Join(labels, ",")] = m.GetCounter().GetValue()
		}
	}
	return out
}

func counterDelta(before, after map[string]float64) string {
	var moved []string
	for k, v := range after {
		if d := v - before[k]; d != 0 {
			moved = append(moved, fmt.Sprintf("%s +%v", k, d))
		}
	}
	sort.Strings(moved)
	if len(moved) == 0 {
		return "(none)"
	}
	return strings.Join(moved, "; ")
}

// renderPinned renders a value whole, unexported fields included, pointers
// followed and map keys sorted, so two answers render alike exactly when they
// are alike.
func renderPinned(v reflect.Value) string {
	switch v.Kind() {
	case reflect.Invalid:
		return "<invalid>"
	case reflect.Ptr, reflect.Interface:
		if v.IsNil() {
			return "nil"
		}
		return "&" + renderPinned(v.Elem())
	case reflect.Struct:
		var b strings.Builder
		b.WriteString(v.Type().Name() + "{")
		for i := 0; i < v.NumField(); i++ {
			if i > 0 {
				b.WriteString(", ")
			}
			b.WriteString(v.Type().Field(i).Name + ":" + renderPinned(v.Field(i)))
		}
		b.WriteString("}")
		return b.String()
	case reflect.Slice, reflect.Array:
		if v.Kind() == reflect.Slice && v.IsNil() {
			return "nil[]"
		}
		parts := make([]string, v.Len())
		for i := range parts {
			parts[i] = renderPinned(v.Index(i))
		}
		return "[" + strings.Join(parts, ", ") + "]"
	case reflect.Map:
		if v.IsNil() {
			return "nilmap"
		}
		keys := v.MapKeys()
		parts := make([]string, 0, len(keys))
		for _, k := range keys {
			parts = append(parts, renderPinned(k)+":"+renderPinned(v.MapIndex(k)))
		}
		sort.Strings(parts)
		return "map[" + strings.Join(parts, ", ") + "]"
	case reflect.String:
		return fmt.Sprintf("%q", v.String())
	case reflect.Bool:
		return fmt.Sprint(v.Bool())
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
		return fmt.Sprint(v.Int())
	case reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64:
		return fmt.Sprint(v.Uint())
	case reflect.Float32, reflect.Float64:
		return fmt.Sprint(v.Float())
	case reflect.Func:
		if v.IsNil() {
			return "nilfunc"
		}
		return "func"
	}
	return "<" + v.Kind().String() + ">"
}

func renderAnswer(vals ...any) string {
	parts := make([]string, len(vals))
	for i, v := range vals {
		parts[i] = renderPinned(reflect.ValueOf(v))
	}
	return strings.Join(parts, " | ")
}

// seamPinLines drives every seam over every case and returns one line per case.
func seamPinLines(t *testing.T) []string {
	t.Helper()
	var lines []string
	pin := func(seam, name string, answer func() string) {
		before := counterSnapshot(t)
		got := answer()
		lines = append(lines, seam+" / "+name+" => "+got+" || counter: "+counterDelta(before, counterSnapshot(t)))
	}

	for _, c := range seamPinVerdicts() {
		// wcp: the workflow step gate, through its entry.
		withStepGateEngine(t, c.v)
		pin("wcp", c.name, func() string {
			ev, res, _ := stepGateDecide(wcpSubjectContext(), seamStepContext(), OrchestratorRequest{RequestID: "req-pin"})
			return renderAnswer(ev, res)
		})

		// map: the multi-agent checker, off and at a conditional's branch.
		for _, branch := range []bool{false, true} {
			withMAPEngine(t, c.v)
			ctx := mapSubjectContext()
			label := c.name
			if branch {
				ctx, label = withBranchPosition(ctx), c.name+" at a branch"
			}
			pin("map", label, func() string {
				res, _ := mapStepDecide(ctx, WorkflowStep{Name: "s", Type: "llm-call", Prompt: "p"}, StepContent{}, mapExecution())
				return renderAnswer(res)
			})
		}

		// route: the two request routes, over unrestricted routes and over
		// restrictions that permit nothing (with and without the segment cause).
		for _, routes := range []struct {
			label string
			r     routeEffects
		}{
			{"", routeEffects{PreferredProvider: "prov-a", RoutingReason: "pinned", AllowedProviders: []string{"prov-a"}, Restricted: true}},
			{" where the routes permit nothing", routeEffects{Restricted: true}},
			{" where a segment took the last provider", routeEffects{Restricted: true, SegmentNotEstablished: true}},
		} {
			_, src := withRouteRequestEngine(t, c.v)
			src.routes = routes.r
			h := http.Header{}
			h.Set("X-Org-ID", "org-route")
			h.Set("X-Client-ID", "client-route")
			pin("route", c.name+routes.label, func() string {
				d := decideRouteRequestOnce(context.Background(), h, OrchestratorRequest{RequestID: "req-pin", Query: "q", Client: ClientContext{OrgID: "org-route"}}, "llm.completion")
				return renderAnswer(d)
			})
		}
	}
	return lines
}

func TestTheThreeSeamsAnswerEveryVerdictShapeAsPinned(t *testing.T) {
	got := strings.Join(seamPinLines(t), "\n") + "\n"
	if *updateSeamPins {
		if err := os.MkdirAll(filepath.Dir(seamPinGolden), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(seamPinGolden, []byte(got), 0o644); err != nil { //nolint:gosec // a test golden
			t.Fatal(err)
		}
		t.Logf("wrote %s (%d lines)", seamPinGolden, strings.Count(got, "\n"))
		return
	}
	want, err := os.ReadFile(seamPinGolden)
	if err != nil {
		t.Fatalf("read %s: %v", seamPinGolden, err)
	}
	if got == string(want) {
		return
	}
	gotLines, wantLines := strings.Split(got, "\n"), strings.Split(string(want), "\n")
	for i := 0; i < len(gotLines) || i < len(wantLines); i++ {
		var g, w string
		if i < len(gotLines) {
			g = gotLines[i]
		}
		if i < len(wantLines) {
			w = wantLines[i]
		}
		if g != w {
			t.Errorf("pin %d moved:\n  pinned: %s\n  now:    %s", i+1, w, g)
		}
	}
}
