// Copyright 2026 AxonFlow
// SPDX-License-Identifier: BUSL-1.1

package agent

import (
	"bytes"
	"context"
	"database/sql"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/http/httptest"
	"os"
	"strings"
	"testing"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

// These tests exercise the new lifecycle semantics introduced alongside ADR-048:
// 1-year expires_at default (replacing 30 days), terminated_at tombstone semantics
// in the auth path, and the PK-collision retry in the registration handler.
//
// DB tests connect to a real Postgres via DATABASE_URL (CI provides it via the
// test-community.yml workflow's service container) and skip locally when not set.
// Pure-function tests (unique-violation detection, disclaimer text) run anywhere.

// connectAndCleanDB returns a connected *sql.DB and a cleanup function that
// removes any community_saas_registrations rows the test created. Skips the
// test if DATABASE_URL is unset.
// connectAndCleanDB returns a connected *sql.DB and a cleanup function. The
// cleanup function:
//
//  1. Resets the package-level IP rate limiter so tests don't accumulate state
//     across invocations (registration handler is rate-limited 5/IP/hr — without
//     this, sequentially-running tests using the same RemoteAddr trip the limit
//     once we add a 6th test).
//  2. Deletes any rows whose tenant_id starts with `tenantPrefix`. The prefix
//     MUST be tighter than `cs_` (which would match every community-saas tenant
//     in the database — both ours and any other concurrent test's). Use a
//     test-specific prefix like `cs_test_<scenario>_` so the production-shaped
//     `cs_<uuid>` tenants generated by the registration handler don't match.
//  3. Closes the DB connection.
//
// Skips the test if DATABASE_URL is unset.
func connectAndCleanDB(t *testing.T, tenantPrefix string) (*sql.DB, func()) {
	t.Helper()
	if !strings.HasPrefix(tenantPrefix, "cs_test_") {
		t.Fatalf("test bug: connectAndCleanDB requires a tenant prefix starting with 'cs_test_' to "+
			"avoid mass-deleting non-test rows; got %q", tenantPrefix)
	}
	dbURL := os.Getenv("DATABASE_URL")
	if dbURL == "" {
		t.Skip("Skipping DB integration test: DATABASE_URL not set")
	}
	db, err := sql.Open("postgres", dbURL)
	if err != nil {
		t.Fatalf("sql.Open: %v", err)
	}
	if err := db.Ping(); err != nil {
		_ = db.Close()
		t.Fatalf("db.Ping: %v", err)
	}
	resetRegistrationIPTracker()
	cleanup := func() {
		_, _ = db.ExecContext(context.Background(),
			`DELETE FROM community_saas_registrations WHERE tenant_id LIKE $1`,
			tenantPrefix+"%")
		resetRegistrationIPTracker()
		_ = db.Close()
	}
	return db, cleanup
}

// resetRegistrationIPTracker clears all per-IP counters in the package-level
// rate-limit tracker. Test-only helper. Production code never calls this.
func resetRegistrationIPTracker() {
	regIPTracker.mu.Lock()
	defer regIPTracker.mu.Unlock()
	regIPTracker.entries = make(map[string]*ipRegistrationEntry)
}

// TestValidateCommunityRegistration_DB_TerminatedTenant asserts that a row with
// terminated_at non-NULL returns ErrRegistrationTerminated, distinct from the
// pre-existing ErrRegistrationDisabled and ErrRegistrationExpired errors. This
// is the auth predicate the daily inactivity sweep depends on.
func TestValidateCommunityRegistration_DB_TerminatedTenant(t *testing.T) {
	db, cleanup := connectAndCleanDB(t, "cs_test_term_")
	defer cleanup()

	tenantID := "cs_test_term_" + uuid.NewString()
	// Insert a fully active row first
	_, err := db.ExecContext(context.Background(),
		`INSERT INTO community_saas_registrations (tenant_id, secret_hash, secret_prefix, org_id, expires_at)
		 VALUES ($1, '$2a$12$placeholderhashplaceholderhashplaceholderhashplaceholdr', 'placehold', 'community-saas', NOW() + INTERVAL '1 year')`,
		tenantID)
	if err != nil {
		t.Fatalf("seed insert: %v", err)
	}
	// Then mark it terminated (simulating sweep)
	_, err = db.ExecContext(context.Background(),
		`UPDATE community_saas_registrations SET terminated_at = NOW(), secret_hash = '' WHERE tenant_id = $1`,
		tenantID)
	if err != nil {
		t.Fatalf("terminate update: %v", err)
	}

	got := validateCommunityRegistration(context.Background(), db, tenantID, "any-secret")
	if !errors.Is(got, ErrRegistrationTerminated) {
		t.Errorf("expected ErrRegistrationTerminated, got %v", got)
	}
}

// TestValidateCommunityRegistration_DB_DisabledStillBeatsTerminated asserts that
// when both disabled_at and terminated_at would apply (operator marked disabled,
// then sweep also terminated), the auth path reports terminated — the more
// severe state — so the client gets the actionable "re-register" message rather
// than the operator-action message.
func TestValidateCommunityRegistration_DB_DisabledStillBeatsTerminated(t *testing.T) {
	db, cleanup := connectAndCleanDB(t, "cs_test_dst_")
	defer cleanup()

	tenantID := "cs_test_dst_" + uuid.NewString()
	_, err := db.ExecContext(context.Background(),
		`INSERT INTO community_saas_registrations
		 (tenant_id, secret_hash, secret_prefix, org_id, expires_at, disabled_at, terminated_at)
		 VALUES ($1, '', '', 'community-saas',
		         NOW() + INTERVAL '1 year', NOW() - INTERVAL '1 hour', NOW() - INTERVAL '1 minute')`,
		tenantID)
	if err != nil {
		t.Fatalf("seed insert: %v", err)
	}
	got := validateCommunityRegistration(context.Background(), db, tenantID, "x")
	if !errors.Is(got, ErrRegistrationTerminated) {
		t.Errorf("expected ErrRegistrationTerminated (most severe), got %v", got)
	}
}

// TestHandleCommunityRegister_DB_OneYearExpiry covers the bumped TTL: a fresh
// registration must record expires_at ~1 year from now, not the pre-ADR-048
// 30-day window. Tolerance is ±10 minutes to account for clock + INSERT latency.
func TestHandleCommunityRegister_DB_OneYearExpiry(t *testing.T) {
	// Specific cleanup prefix can't match handler-generated cs_<uuid> tenants —
	// production rows are protected; only this test's own row is cleaned up
	// via the tenant_id-specific DELETE registered with t.Cleanup below.
	db, cleanup := connectAndCleanDB(t, "cs_test_oneyear_")
	defer cleanup()

	resp := registerOnceWithIP(t, db, "", "10.0.0.10:1234")
	t.Cleanup(func() {
		_, _ = db.ExecContext(context.Background(),
			`DELETE FROM community_saas_registrations WHERE tenant_id = $1`, resp.TenantID)
	})
	parsed, err := time.Parse(time.RFC3339, resp.ExpiresAt)
	if err != nil {
		t.Fatalf("parse expires_at: %v", err)
	}
	expected := time.Now().UTC().Add(communitySaasRegistrationTTL)
	delta := parsed.Sub(expected)
	if delta < -10*time.Minute || delta > 10*time.Minute {
		t.Errorf("expires_at delta from expected 1yr = %v (parsed=%v expected=%v)", delta, parsed, expected)
	}
	var dbExpiresAt time.Time
	if err := db.QueryRowContext(context.Background(),
		`SELECT expires_at FROM community_saas_registrations WHERE tenant_id = $1`,
		resp.TenantID).Scan(&dbExpiresAt); err != nil {
		t.Fatalf("read expires_at: %v", err)
	}
	if got := dbExpiresAt.Sub(time.Now().UTC()); got < 360*24*time.Hour || got > 370*24*time.Hour {
		t.Errorf("DB expires_at outside [360d, 370d] window: %v", got)
	}
}

// TestHandleCommunityRegister_DB_DisclaimerNote asserts the response Note field
// matches the canonical disclaimer text and surfaces the operational facts
// customers need: Free-tier limits, lifecycle sweep rules, and the Pro
// upgrade path. Quality-of-service framing belongs in ToS / Privacy, not
// here.
func TestHandleCommunityRegister_DB_DisclaimerNote(t *testing.T) {
	db, cleanup := connectAndCleanDB(t, "cs_test_disclaimer_")
	defer cleanup()

	resp := registerOnceWithIP(t, db, "", "10.0.0.11:1234")
	t.Cleanup(func() {
		_, _ = db.ExecContext(context.Background(),
			`DELETE FROM community_saas_registrations WHERE tenant_id = $1`, resp.TenantID)
	})
	if resp.Note != communitySaasDisclaimerNote {
		t.Errorf("response Note does not match canonical disclaimer\n  got:  %q\n  want: %q",
			resp.Note, communitySaasDisclaimerNote)
	}
	// Spot-check the disclaimer surfaces the operational facts (Free-tier
	// limits, lifecycle sweep, Pro upgrade pointer)
	mustContain := []string{
		"3-day audit retention",
		"200 events/day",
		"3 months of inactivity",
		"1 year from creation",
		"Plugin Pro",
		"30-day retention",
		"1,000 events/day",
		"$9.99",
		"https://www.getaxonflow.com/pricing/",
	}
	for _, s := range mustContain {
		if !strings.Contains(resp.Note, s) {
			t.Errorf("disclaimer note missing required substring %q", s)
		}
	}
}

// TestHandleCommunityRegister_DB_PKCollisionRetry forces the registration handler
// to retry on a Postgres unique violation. Validates the defense-in-depth retry
// loop introduced for the never-reuse-tenant_id guarantee.
func TestHandleCommunityRegister_DB_PKCollisionRetry(t *testing.T) {
	db, cleanup := connectAndCleanDB(t, "cs_test_collide_")
	defer cleanup()

	// Pre-seed a row whose tenant_id will be the first UUID our mock returns
	collideUUID := uuid.NewString()
	collideTenant := communitySaasTenantPrefix + collideUUID
	_, err := db.ExecContext(context.Background(),
		`INSERT INTO community_saas_registrations
		 (tenant_id, secret_hash, secret_prefix, org_id, expires_at)
		 VALUES ($1, '', '', 'community-saas', NOW() + INTERVAL '1 year')`,
		collideTenant)
	if err != nil {
		t.Fatalf("seed collide row: %v", err)
	}
	defer func() {
		_, _ = db.ExecContext(context.Background(),
			`DELETE FROM community_saas_registrations WHERE tenant_id = $1`, collideTenant)
	}()

	// First call returns the colliding UUID; second call returns a fresh one.
	original := uuidNewString
	defer func() { uuidNewString = original }()
	freshUUID := uuid.NewString()
	calls := 0
	uuidNewString = func() string {
		calls++
		if calls == 1 {
			return collideUUID
		}
		return freshUUID
	}

	resp := registerOnceWithIP(t, db, "pk-retry-test", "10.0.0.12:1234")
	t.Cleanup(func() {
		_, _ = db.ExecContext(context.Background(),
			`DELETE FROM community_saas_registrations WHERE tenant_id = $1`, resp.TenantID)
	})

	if calls != 2 {
		t.Errorf("expected 2 uuid calls (1 collision + 1 retry), got %d", calls)
	}
	if resp.TenantID != communitySaasTenantPrefix+freshUUID {
		t.Errorf("expected retry to land on fresh UUID; got TenantID=%s", resp.TenantID)
	}
}

// TestHandleCommunityRegister_DB_PKExhaustedRetries covers the impossible-state
// path where every retry collides. The handler must surface 500 rather than
// loop forever or silently succeed with a non-fresh row.
func TestHandleCommunityRegister_DB_PKExhaustedRetries(t *testing.T) {
	db, cleanup := connectAndCleanDB(t, "cs_test_exhaust_")
	defer cleanup()

	collideUUID := uuid.NewString()
	collideTenant := communitySaasTenantPrefix + collideUUID
	_, err := db.ExecContext(context.Background(),
		`INSERT INTO community_saas_registrations
		 (tenant_id, secret_hash, secret_prefix, org_id, expires_at)
		 VALUES ($1, '', '', 'community-saas', NOW() + INTERVAL '1 year')`,
		collideTenant)
	if err != nil {
		t.Fatalf("seed collide row: %v", err)
	}
	defer func() {
		_, _ = db.ExecContext(context.Background(),
			`DELETE FROM community_saas_registrations WHERE tenant_id = $1`, collideTenant)
	}()

	original := uuidNewString
	defer func() { uuidNewString = original }()
	calls := 0
	uuidNewString = func() string {
		calls++
		return collideUUID // always collide
	}

	body, _ := json.Marshal(registrationRequest{Label: "exhaustion-test"})
	req := httptest.NewRequest("POST", "/api/v1/register", bytes.NewReader(body))
	req.Header.Set("Content-Type", "application/json")
	req.RemoteAddr = "10.0.0.99:1234" // fresh IP so rate limiter doesn't trip
	rr := httptest.NewRecorder()
	handleCommunityRegister(db).ServeHTTP(rr, req)

	if rr.Code != http.StatusInternalServerError {
		t.Errorf("expected 500 after exhausted retries, got %d (body=%s)", rr.Code, rr.Body.String())
	}
	if calls != communitySaasMaxRegistrationRetries {
		t.Errorf("expected exactly %d retry attempts, got %d", communitySaasMaxRegistrationRetries, calls)
	}
}

// TestIsUniqueViolation covers the SQLSTATE 23505 detection helper. Pure unit
// test; doesn't need DB.
func TestIsUniqueViolation(t *testing.T) {
	cases := []struct {
		name string
		err  error
		want bool
	}{
		{"nil", nil, false},
		{"plain error", errors.New("not a pq error"), false},
		{"pq error 23505", &pq.Error{Code: "23505"}, true},
		{"pq error 42P01 (other)", &pq.Error{Code: "42P01"}, false},
		{"wrapped pq error 23505", fmt.Errorf("wrapped: %w", &pq.Error{Code: "23505"}), true},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			if got := isUniqueViolation(c.err); got != c.want {
				t.Errorf("isUniqueViolation(%v) = %v, want %v", c.err, got, c.want)
			}
		})
	}
}

// registerOnceWithIP drives the registration handler once with the supplied
// remoteAddr and parses the response body into registrationResponse. Each test
// passes its own unique IP so the IP rate-limiter (5 registrations/IP/hour)
// never accumulates count across tests — important now and as the suite grows.
func registerOnceWithIP(t *testing.T, db *sql.DB, label, remoteAddr string) registrationResponse {
	t.Helper()
	body, _ := json.Marshal(registrationRequest{Label: label})
	req := httptest.NewRequest("POST", "/api/v1/register", bytes.NewReader(body))
	req.Header.Set("Content-Type", "application/json")
	req.RemoteAddr = remoteAddr
	rr := httptest.NewRecorder()
	handleCommunityRegister(db).ServeHTTP(rr, req)
	if rr.Code != http.StatusCreated {
		t.Fatalf("registerOnceWithIP(%s): expected 201, got %d (body=%s)", remoteAddr, rr.Code, rr.Body.String())
	}
	var resp registrationResponse
	if err := json.Unmarshal(rr.Body.Bytes(), &resp); err != nil {
		t.Fatalf("registerOnceWithIP: parse response: %v", err)
	}
	return resp
}
