// Copyright 2025 AxonFlow
// SPDX-License-Identifier: BUSL-1.1

package agent

import (
	"context"
	"database/sql"
	"encoding/json"
	"log"
	"strconv"
	"strings"
	"time"

	"github.com/lib/pq"

	"axonflow/platform/agent/fincrime"
	sharedaudit "axonflow/platform/shared/audit"
	sharedpolicy "axonflow/platform/shared/policy"
)

// buildRicherCheckInputBlock assembles the Plugin Batch 1 fields that extend
// MCPCheckInputResponse on a block: policy_matches (with risk_level +
// allow_override), the top-level risk_level taken from the first overridable
// match (or the first match if none are overridable), and override_available
// plus override_existing_id so the plugin can render a "press this to
// unblock" affordance.
//
// The decision_id is generated by the caller so it can be written into the
// audit entry before this helper runs — the id must survive into
// audit_logs.policy_details so the explain endpoint can resolve it later.
//
// The helper is best-effort. Any DB failure (SQL error, missing column,
// etc.) logs and returns zero values — the block itself is already
// authoritative, so we never fail a block because of a lookup error.
func buildRicherCheckInputBlock(
	ctx context.Context,
	db *sql.DB,
	tenantID, userEmail string,
	matched []sharedpolicy.PolicyMatch,
) (matches []RicherPolicyMatch, topRisk string, overrideAvailable *bool, overrideID string) {
	if db == nil || len(matched) == 0 {
		return nil, "", nil, ""
	}

	// #3048: static_policies is RLS-enabled — the by-slug lookups below need
	// an org scope under axonflow_app_role. The caller's org is the scope for
	// tenant/org-tier policies; the helpers fall back to the 'global' scope
	// for system-tier rows internally.
	scopeOrg := OrgIDFromContext(ctx)
	if scopeOrg == "" {
		scopeOrg = tenantID
	}

	matches = make([]RicherPolicyMatch, 0, len(matched))
	var firstOverridablePolicyID string
	for _, m := range matched {
		risk, allowOverride, version, err := lookupPolicyMeta(ctx, db, scopeOrg, m.PolicyID)
		if err != nil {
			log.Printf("richer context: policy lookup failed for %s: %v", m.PolicyID, err)
			// Emit a stub entry so the plugin sees it was matched even when
			// we can't resolve the override flag.
			matches = append(matches, RicherPolicyMatch{
				PolicyID:   m.PolicyID,
				PolicyName: m.PolicyName,
			})
			continue
		}
		matches = append(matches, RicherPolicyMatch{
			PolicyID:      m.PolicyID,
			PolicyName:    m.PolicyName,
			RiskLevel:     risk,
			AllowOverride: allowOverride,
			Version:       version,
		})
		// Top-level risk_level: prefer first overridable non-critical match
		// so the plugin UI can default to showing the "request override"
		// CTA. Fall back to the first match if none overridable.
		if topRisk == "" || (firstOverridablePolicyID == "" && allowOverride && risk != "critical") {
			topRisk = risk
			if allowOverride && risk != "critical" {
				firstOverridablePolicyID = m.PolicyID
			}
		}
	}

	// override_available + override_existing_id: scoped to
	// (tenant, user, first overridable policy). Critical-risk policies never
	// qualify — the DB trigger guarantees this but we belt-and-suspenders
	// here so the plugin doesn't render an "override" button for something
	// that will 403 anyway.
	//
	// #2896: a client-shared pseudo-identity gets NO override affordance —
	// offering the CTA would let the plugin create an override that either
	// never applies (identity mismatch across planes) or applies to every
	// caller on the client. The block response stays a plain block.
	if firstOverridablePolicyID == "" || userEmail == "" || isClientSharedPseudoIdentity(userEmail) {
		return matches, topRisk, nil, ""
	}

	available := false
	overrideAvailable = &available

	activeID, found, err := lookupActiveOverride(ctx, db, tenantID, userEmail, firstOverridablePolicyID)
	if err != nil {
		log.Printf("richer context: active-override lookup failed for %s: %v",
			firstOverridablePolicyID, err)
		return matches, topRisk, overrideAvailable, ""
	}
	if found {
		overrideID = activeID
	}
	// allow_override=true + non-critical means the user COULD create an
	// override — so override_available is true regardless of whether one
	// is already active. The plugin distinguishes the two via
	// override_existing_id being set.
	*overrideAvailable = true
	return matches, topRisk, overrideAvailable, overrideID
}

// lookupPolicyMeta fetches risk_level + allow_override + version for a
// policy. Returns ("", false, 0, nil) if the policy isn't in the table
// (non-fatal — dynamic policies don't live in static_policies).
//
// version is the live `static_policies.version` column (#1983 / α1):
// callers stamp the value into audit_logs.policy_details so the explain
// endpoint can answer "which version evaluated me?" without a separate
// lookup. Forward-only — pre-α1 decisions surface no version.
//
// #3048: static_policies is RLS-enabled (mig 018) — the old bare read
// matched zero rows under axonflow_app_role, so every matched policy lost
// its risk/override metadata. Matched policies are either the caller org's
// own rows or the shared system rows (org_id='global', mig 153), so the
// read is a two-scope pass: scopeOrg first, 'global' on miss. An empty
// scopeOrg keeps the legacy bare read (owner-pool contexts).
func lookupPolicyMeta(ctx context.Context, db *sql.DB, scopeOrg, policyID string) (string, bool, int, error) {
	var risk sql.NullString
	var allowOverride sql.NullBool
	var version sql.NullInt64
	const query = `
		SELECT risk_level, allow_override, version
		FROM static_policies
		WHERE policy_id = $1
		LIMIT 1
	`
	scan := func(row *sql.Row) error { return row.Scan(&risk, &allowOverride, &version) }

	var err error
	if scopeOrg == "" {
		err = scan(db.QueryRowContext(ctx, query, policyID))
	} else {
		err = WithOrgScope(ctx, db, scopeOrg, func(tx *sql.Tx) error {
			return scan(tx.QueryRowContext(ctx, query, policyID))
		})
		if err == sql.ErrNoRows && scopeOrg != GlobalOrgSentinel {
			err = WithOrgScope(ctx, db, GlobalOrgSentinel, func(tx *sql.Tx) error {
				return scan(tx.QueryRowContext(ctx, query, policyID))
			})
		}
	}
	if err == sql.ErrNoRows {
		return "", false, 0, nil
	}
	if err != nil {
		return "", false, 0, err
	}
	return risk.String, allowOverride.Bool, int(version.Int64), nil
}

// collectPolicyVersions distills RicherPolicyMatch.Version values into the
// { policy_id → version } map shape carried by MCPQueryAuditEntry +
// audit_logs.policy_details JSONB (#1983 / α1). Returns nil when no match
// has a known version so audit consumers see omitempty rather than `{}`.
func collectPolicyVersions(matches []RicherPolicyMatch) map[string]int {
	if len(matches) == 0 {
		return nil
	}
	out := make(map[string]int, len(matches))
	for _, m := range matches {
		if m.PolicyID != "" && m.Version > 0 {
			out[m.PolicyID] = m.Version
		}
	}
	if len(out) == 0 {
		return nil
	}
	return out
}

// lookupPolicyVersionsByID returns version numbers keyed by policy_id for the
// given list. Used by the check-output handler to attach policy_version to
// audit entries when static-policy matches fire (#1983 / α1). Single round
// trip via ANY($1::text[]); missing policies (dynamic, ad-hoc) simply don't
// appear in the result map. Best-effort — DB errors return an empty map and
// the audit write proceeds without policy_versions rather than failing the
// decision.
func lookupPolicyVersionsByID(ctx context.Context, db *sql.DB, policyIDs []string) map[string]int {
	if db == nil || len(policyIDs) == 0 {
		return nil
	}
	const query = `
		SELECT policy_id, version
		FROM static_policies
		WHERE policy_id = ANY($1)
	`
	out := make(map[string]int, len(policyIDs))
	collect := func(rows *sql.Rows, qErr error) {
		if qErr != nil {
			log.Printf("richer context: policy_versions batch lookup failed: %v", qErr)
			return
		}
		defer func() { _ = rows.Close() }()
		for rows.Next() {
			var pid string
			var ver sql.NullInt64
			if err := rows.Scan(&pid, &ver); err != nil {
				log.Printf("richer context: policy_versions row scan failed: %v", err)
				continue
			}
			if ver.Valid {
				out[pid] = int(ver.Int64)
			}
		}
		if err := rows.Err(); err != nil {
			log.Printf("richer context: policy_versions iteration failed: %v", err)
		}
	}

	// #3048: static_policies is RLS-enabled — under axonflow_app_role the
	// old bare batch read returned zero rows and audit rows lost their
	// policy_versions map. The matched ids span the caller org's rows and
	// the shared 'global' system rows, so read BOTH scopes and merge (on
	// owner pools both passes see the full set — the map merge is
	// idempotent). An empty caller org keeps the legacy bare read.
	scopeOrg := OrgIDFromContext(ctx)
	if scopeOrg == "" {
		rows, qErr := db.QueryContext(ctx, query, pq.Array(policyIDs))
		collect(rows, qErr)
	} else {
		scopes := []string{scopeOrg}
		if scopeOrg != GlobalOrgSentinel {
			scopes = append(scopes, GlobalOrgSentinel)
		}
		for _, scope := range scopes {
			if err := WithOrgScope(ctx, db, scope, func(tx *sql.Tx) error {
				rows, qErr := tx.QueryContext(ctx, query, pq.Array(policyIDs))
				collect(rows, qErr)
				return nil
			}); err != nil {
				log.Printf("richer context: policy_versions scoped lookup (%s) failed: %v", scope, err)
			}
		}
	}

	if len(out) == 0 {
		return nil
	}
	return out
}

// lookupActiveOverride returns (id, true, nil) when the caller already has
// a live (non-revoked, non-expired) override on the policy, or ("",
// false, nil) otherwise. Scoped to (tenant, user, policy). The tool_signature
// dimension is explicitly ignored — on the /api/v1/mcp/check-input path
// there's no canonical "tool" identity, so we check for any override on
// the policy rather than tool-scoped ones.
//
// Accepts either the human-readable policy slug (sys_sqli_admin_bypass) or
// a UUID. policy_overrides.policy_id is UUID-typed; static_policies.policy_id
// is the slug — so a join via static_policies is required when the caller
// passes the slug. We do the join in a single statement so the index on
// static_policies.policy_id stays hot.
func lookupActiveOverride(ctx context.Context, db *sql.DB, tenantID, userEmail, policySlugOrUUID string) (string, bool, error) {
	// #3048: both tables here are RLS-enabled (static_policies mig 018,
	// policy_overrides mig 110) and live in DIFFERENT org scopes when the
	// policy is a system-tier row: the policy carries org_id='global' while
	// the override row carries the caller's org. The old single statement
	// resolved the slug via a subselect INSIDE the caller's (unset) scope —
	// under axonflow_app_role it matched nothing and every active override
	// silently stopped applying. Resolve the policy UUID first (caller org
	// scope, then 'global'), then read the override under the caller's org
	// scope. An empty caller org keeps the legacy bare single statement
	// (owner-pool contexts, RLS bypassed).
	scopeOrg := OrgIDFromContext(ctx)
	if scopeOrg == "" {
		scopeOrg = tenantID
	}

	var id string
	if scopeOrg == "" {
		// #3065 (R3 round 2): this branch used to run a BARE read — no
		// WithOrgScope wrap and no org predicate — with
		// `(po.tenant_id = $3 OR po.tenant_id IS NULL)` and $3 empty. On an
		// owner-pool deployment (AXONFLOW_DB_USE_APP_ROLE unset, the
		// docker-compose default) RLS is bypassed, so that resolved ANY org's
		// org-scoped override for the given created_by. It is the same
		// "unknown caller org falls back to a bare read" fallback that
		// PolicyOverrideRepository.GetByID carried until this change removed
		// it one file over.
		//
		// Fail closed instead: with no org to authorize against there is no
		// override to apply, so the ADR-044 allow-flip does not fire and the
		// underlying deny stands. That is the safe direction — the override
		// exists only to RELAX a decision.
		return "", false, nil
	}

	const resolveQuery = `
		SELECT sp.id FROM static_policies sp
		WHERE sp.policy_id = $1
		LIMIT 1
	`
	var policyUUID string
	resolve := func(scope string) error {
		return WithOrgScope(ctx, db, scope, func(tx *sql.Tx) error {
			return tx.QueryRowContext(ctx, resolveQuery, policySlugOrUUID).Scan(&policyUUID)
		})
	}
	err := resolve(scopeOrg)
	if err == sql.ErrNoRows && scopeOrg != GlobalOrgSentinel {
		err = resolve(GlobalOrgSentinel)
	}
	if err == sql.ErrNoRows {
		return "", false, nil
	}
	if err != nil {
		return "", false, err
	}

	err = WithOrgScope(ctx, db, scopeOrg, func(tx *sql.Tx) error {
		return tx.QueryRowContext(ctx, `
			SELECT po.id
			FROM policy_overrides po
			WHERE po.policy_id::text = $1
			  AND po.created_by = $2
			  AND (po.tenant_id = $3 OR po.tenant_id IS NULL)
			  AND po.revoked_at IS NULL
			  AND (po.expires_at IS NULL OR po.expires_at > NOW())
			ORDER BY po.created_at DESC
			LIMIT 1
		`, policyUUID, userEmail, tenantID).Scan(&id)
	})
	if err == sql.ErrNoRows {
		return "", false, nil
	}
	if err != nil {
		return "", false, err
	}
	return id, true, nil
}

// applyOverrideToCheckInputBlock applies an active session override to a
// matched-policy block. Returns (overrideID, &match, true) when the block is
// suppressed — caller should treat the request as allowed and emit an
// override_used audit event — or ("", nil, false) when no applicable
// override exists and the block stands.
//
// The matched RicherPolicyMatch is returned so the caller can stamp the
// overridden policy's version into the override_used audit event
// (#1983 / α1). Returning a pointer keeps the no-override case allocation
// free.
//
// ADR-044 invariants enforced:
//   - Only non-critical, allow_override=true policies are overridable
//   - Must be scoped to (tenant, user, policy)
//   - Only live overrides (non-revoked, non-expired) qualify
//
// This mirrors orchestrator.ApplyOverrideToResult for the WCP path — the
// same semantics applied to the MCP check-input path so the plugin and
// SDK see consistent behavior regardless of which surface fired the
// request. Deliberately NOT segment-aware: RicherPolicyMatch carries no
// SegmentID, and none was added by #3296 Slice 2 — adding a segment
// exclusion here would break the stated parity with
// orchestrator.ApplyOverrideToResult, which was itself deliberately made
// NOT segment-exclusive by #3239 (see platform/orchestrator/
// override_enforcement.go's doc comment and platform/shared/policy/
// override.go's package doc for the full rationale/evidence). The
// SEPARATE admin tier-downgrade override mechanism
// (StaticPolicyRepository.GetEffective) DOES exclude segment-scoped
// policies — that is a different code path from this one.
func applyOverrideToCheckInputBlock(
	ctx context.Context,
	db *sql.DB,
	tenantID, userEmail string,
	matches []RicherPolicyMatch,
) (string, *RicherPolicyMatch, bool) {
	// #2896: never flip a deny for a client-shared pseudo-identity — an
	// override keyed to "mcp-client:<id>" would be one caller's override
	// applied to EVERY caller on that client (ADR-044 scopes overrides to a
	// user, not a client). Fail closed: the block stands.
	if db == nil || userEmail == "" || isClientSharedPseudoIdentity(userEmail) || len(matches) == 0 {
		return "", nil, false
	}
	for i := range matches {
		m := matches[i]
		// Eligibility gate factored into the shared primitive (#3296 Slice 2)
		// — identical logic to orchestrator.ApplyOverrideToResult /
		// SelectOverridablePolicy. See platform/shared/policy/override.go.
		if !sharedpolicy.IsOverrideEligible(m.RiskLevel, m.AllowOverride) {
			continue
		}
		id, found, err := lookupActiveOverride(ctx, db, tenantID, userEmail, m.PolicyID)
		if err != nil {
			log.Printf("apply override: lookup failed for %s: %v", m.PolicyID, err)
			continue
		}
		if found {
			return id, &matches[i], true
		}
	}
	return "", nil, false
}

// writeOverrideUsedEvent records an override_used audit event for the MCP
// check-input path. The orchestrator emits matching events for its own
// paths; this keeps the override audit trail consistent across surfaces.
//
// policyID + policyVersion identify the policy whose block was unblocked
// by this override (#1983 / α1). They land in policy_details JSONB so the
// explain endpoint can surface "which version of which policy was overridden"
// without re-deriving from the override row. Both are best-effort: empty
// policyID / zero policyVersion are simply omitted from the JSONB so we
// never block an override write on an unknown match.
func writeOverrideUsedEvent(
	ctx context.Context,
	db *sql.DB,
	overrideID, decisionID, tenantID, orgID, clientID, userEmail string,
	policyID string, policyName string, policyVersion int,
	correlationID string,
) {
	if db == nil || overrideID == "" {
		return
	}
	details := map[string]interface{}{
		"decision_id": decisionID,
		"override_id": overrideID,
		"event_type":  "override_used",
	}
	if policyID != "" {
		details["policy_id"] = policyID
	}
	// #3365: the overridden match's evaluation-time display name (scalar
	// policy_name, the shared reader's first resolution arm). Previously the
	// event carried the id alone, so the portal rendered it with the
	// "(name not recorded)" marker.
	if policyName != "" {
		details["policy_name"] = policyName
	}
	if policyVersion > 0 {
		details["policy_version"] = policyVersion
		// #3365: the shared reader's version chain (extractVersion /
		// PolicyVersionSQLExpr) resolves policy_versions[id] and
		// policy_matches[0].policy_version but never a top-level scalar, so the
		// scalar above was written and unreadable on every surface. Stamp the
		// id-keyed map alongside it (scalar kept for back-compat readers of the
		// raw JSONB).
		if policyID != "" {
			details["policy_versions"] = map[string]int{policyID: policyVersion}
		}
	}
	// #2598: mirror the correlation key into JSONB (read-path resilience) and the
	// first-class column below, so an override applied mid-chain groups with the
	// other stages of the same logical request.
	if correlationID != "" {
		details["correlation_id"] = correlationID
	}
	detailsJSON, err := json.Marshal(details)
	if err != nil {
		return
	}
	if userEmail == "" {
		userEmail = "unknown@axonflow.local"
	}
	if clientID == "" {
		clientID = "unknown"
	}
	if tenantID == "" {
		tenantID = "unknown"
	}
	// #2592 / ADR-058 Phase 1: dual-write decision_id into the first-class
	// column + stamp plane=mcp (this is the MCP check-input override surface),
	// alongside the JSONB copy. No obligations on an override-used event.
	// #2598: correlation_id (first-class column or NULL → singleton).
	var correlationIDArg interface{}
	if correlationID != "" {
		correlationIDArg = correlationID
	}
	// #2753: per-session identity → audit_logs.session_id (NULL when absent),
	// read from the request context stamped in requireMCPAuth, for parity with
	// the block/redact rows on the same check_policy surface.
	var sessionIDArg interface{}
	if sid := clientSessionIDFromContext(ctx); sid != "" {
		sessionIDArg = sid
	}
	_, _ = db.ExecContext(ctx, `
		INSERT INTO audit_logs (
			id, request_id, timestamp, user_id, user_email, user_role,
			client_id, tenant_id, org_id, request_type, query, query_hash,
			policy_decision, policy_details, decision_id, plane, correlation_id,
			session_id
		) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
	`,
		"audit_used_"+decisionID,
		decisionID,
		time.Now().UTC(),
		0,
		userEmail,
		"user",
		clientID,
		tenantID,
		orgID,
		"override_used",
		"override applied",
		"none",
		// #2641 (AUDIT-C) vocabulary contract (#2638): an override flips a deny to
		// an allow, so the canonical past-tense verdict is "allowed" — NOT the
		// legacy "allow" the agent /decide path still emits. Matches the
		// orchestrator reference (audit_logger.go) so this override-used row reads
		// consistently in the portal decisions feed alongside the redacted/blocked
		// rows this PR adds across the MCP plane.
		mcpVerdictAllowed,
		detailsJSON,
		decisionID,       // decision_id (first-class column)
		PlaneMCP,         // plane
		correlationIDArg, // correlation_id (#2598)
		sessionIDArg,     // session_id (#2753)
	)
}

// MCP-plane canonical policy_decision vocabulary (#2641 / #2638). These are now
// ALIASES onto the single shared vocabulary in platform/shared/audit (#2638
// S-WRITERS const-swap): the same past-tense verdict strings the orchestrator
// reference writer emits, which the customer-portal decisions feed +
// audit-summary mapping both key on, and which the migration-123 CHECK enforces.
// The MCP-plane names are retained (provenance + call-site readability); the
// VALUES come from the shared package so they can never drift from the other
// planes. The full canonical set is allowed | blocked | redacted |
// needs_approval | error; needs_approval is not a terminal verdict any MCP
// surface produces today, so it is intentionally not aliased here (the `unused`
// linter is a CI gate). Add it when a needs_approval-emitting MCP path lands.
const (
	mcpVerdictAllowed  = sharedaudit.DecisionAllowed
	mcpVerdictBlocked  = sharedaudit.DecisionBlocked
	mcpVerdictRedacted = sharedaudit.DecisionRedacted
	mcpVerdictError    = sharedaudit.DecisionError
)

// mcpUnauthenticatedTenant is the fixed tenant_id stamped on a canonical
// audit_logs row recorded for an UNAUTHENTICATED MCP deny (#2641 — the JSON-RPC
// MCPSRV-UNAUTH path and the check-input/check-output auth-failure early return).
// An unauthenticated caller has no trustworthy tenant identity; reusing the
// caller-CLAIMED tenant_id would let an attacker inject rows into another tenant's
// decisions feed (audit spoofing). This sentinel + an empty org_id keep the row
// out of every real tenant's portal scope while still recording the denied attempt
// for security audit.
const mcpUnauthenticatedTenant = "unauthenticated"

// writeMCPDecisionAudit persists a canonical audit_logs row for an MCP-plane
// terminal verdict that carries no rich policy-match payload — i.e. every hole
// AUDIT-C (#2641) closes: a dynamic-only block, a SQLi block, a redact-and-allow,
// a tool-error fail-close, and each pre-policy early-return deny (unauthenticated
// JSON-RPC, tier-gate, daily-cap, session-delete authz, 415/tenant). It is the
// MCP-plane analogue of the orchestrator's canonical response-plane writer
// (#2630, audit_logger.go): policy_decision is the canonical PAST-TENSE vocab
// (allowed|blocked|redacted|needs_approval|error), plane=mcp, decision_id +
// correlation_id are first-class, and redacted_fields is populated on a redaction.
//
// Why a distinct writer rather than recordDecideDecision: writeDecisionAuditLog's
// INSERT (decision_handler.go, owned by another workstream) omits redacted_fields,
// so a redaction routed through it would land with an empty redacted_fields column
// — violating the AUDIT-C DoD. This writer carries it. The legacy mcp_query_audits
// satellite write each caller already performs is preserved and unaffected; the
// canonical row is purely additive (keyed by the SAME decision_id).
//
// Best-effort: a DB error logs and returns. The verdict the PEP already holds is
// authoritative — an audit write never changes the decision (mirrors
// writeExplainableAuditLog / writeDecisionAuditLog).
// toolIdentity is variadic — [0]=server, [1]=tool (mirrors the server/tool
// hierarchy) — so the many existing call sites on managed-connector /
// non-tool paths (which structurally have no tool identity to report,
// #2904/#2905) don't need updating; only the 3 advisory PLANES (check-input,
// check_policy, /decide) have a caller-sent tool identity in scope to pass.
// buildMCPDecisionAuditDetails assembles the policy_details JSONB payload for
// one MCP decision row. Pulled out of writeMCPDecisionAudit as a PURE function
// (mirroring buildDecisionAuditDetails) so the content contract the compliance
// exporters read -- policy_ids first of all (#3243 v9.16.1) -- is pinned by the
// cross-plane writer/reader contract test without a database.
func buildMCPDecisionAuditDetails(decisionID string, policyIDs, reasons, redactedFields []string, correlationID string, policyNames map[string]string, toolIdentity ...string) map[string]interface{} {
	if policyIDs == nil {
		policyIDs = []string{}
	}
	if reasons == nil {
		reasons = []string{}
	}

	details := map[string]interface{}{
		"decision_id": decisionID,
		"source":      "mcp_decision",
		"policy_ids":  policyIDs,
		"reasons":     reasons,
	}
	// #3365: display names for the ids above (evaluation-time map first, then
	// the builtin guard table; a row with NO resolvable name keeps the
	// reader's honest marker, a partially-named row shows the resolved names).
	stampPolicyIdentityNames(details, policyIDs, policyNames)
	if len(reasons) > 0 {
		// explain_handler.go + the portal read policy_details->>'reason' (scalar).
		details["reason"] = strings.Join(reasons, "; ")
	}
	// Mirror redacted_fields into the JSONB too (read-path resilience, matching the
	// decision_id/correlation_id dual-write pattern) so a consumer that only reads
	// policy_details still sees what was masked even if the first-class column is
	// ever rolled back.
	if len(redactedFields) > 0 {
		details["redacted_fields"] = redactedFields
	}
	// #2598: mirror the correlation key into JSONB so this MCP decision groups with
	// the other stages of the same logical request when a W3C traceparent is
	// propagated. Omitted when unset → singleton chain.
	if correlationID != "" {
		details["correlation_id"] = correlationID
	}
	// #2904: tool_server/tool_name — same keys the audit_tool_call path already
	// writes, now populated uniformly across every self-auditing policy plane.
	if len(toolIdentity) > 0 && toolIdentity[0] != "" {
		details["tool_server"] = toolIdentity[0]
	}
	if len(toolIdentity) > 1 && toolIdentity[1] != "" {
		details["tool_name"] = toolIdentity[1]
	}
	return details
}

func writeMCPDecisionAudit(
	ctx context.Context,
	db *sql.DB,
	decisionID, requestID string,
	tenantID, orgID, clientID, userEmail string,
	userIDStr, userRole string,
	requestType, query, queryHash, policyDecision string,
	policyIDs, reasons, redactedFields []string,
	correlationID string,
	policyNames map[string]string,
	toolIdentity ...string,
) {
	if db == nil || decisionID == "" {
		return
	}

	// Coerce user_id into an int — audit_logs.user_id is historically typed that
	// way. Non-numeric ids (plugin pseudo-ids, emails) map to 0; the real identity
	// travels via user_email. Mirrors writeExplainableAuditLog.
	userIDInt := 0
	if n, err := strconv.Atoi(userIDStr); err == nil {
		userIDInt = n
	}

	// ADR-061 / #3329: merge the fincrime attribution recorded on ctx (risk
	// score, ml_inference_layer_status, fincrime policy ids/names/versions)
	// so scored MCP-plane decisions satisfy the #3306 audit contract. No-op
	// for every non-fincrime decision.
	details := fincrime.MergeAuditDetails(ctx,
		buildMCPDecisionAuditDetails(decisionID, policyIDs, reasons, redactedFields, correlationID, policyNames, toolIdentity...))
	// #3365: id-keyed policy_versions, best-effort, AFTER the fincrime merge so
	// the seam's model/pack version strings win (missing-only add). Acted rows
	// only: allow writes must not pay the RLS-scoped batch read per request.
	if actedAuditVerdict(policyDecision) {
		stampMissingPolicyVersions(ctx, db, details)
	}
	detailsJSON, err := json.Marshal(details)
	if err != nil {
		log.Printf("mcp decision audit: marshal failed: %v", err)
		return
	}

	// audit_logs NOT-NULL columns: fall back to placeholders rather than fail the
	// insert (mirrors writeExplainableAuditLog / writeDecisionAuditLog).
	if userEmail == "" {
		userEmail = "unknown@axonflow.local"
	}
	// RBAC-1 (#2920): a least-privilege MCP caller resolves to the authz role
	// RoleNone (""). Stamp the honest "unknown" audit label — NOT a fabricated
	// "service"/"user" — so the trail distinguishes an unresolved-role MCP
	// caller from the real internal-service principal (whose role IS "service")
	// and from a genuine "user"/"admin". Preserves the v9 Fix 5 audit-honesty
	// contract while the returned authz role stays "" for read-scoping (RBAC-3).
	if userRole == "" {
		userRole = "unknown"
	}
	if clientID == "" {
		clientID = "unknown"
	}
	if tenantID == "" {
		tenantID = "unknown"
	}
	if query == "" {
		query = "(empty)"
	}
	if queryHash == "" {
		queryHash = "none"
	}
	if requestID == "" {
		requestID = decisionID
	}

	// redacted_fields is a JSONB column (migration 059). Marshal the slice to a
	// JSON array; pass SQL NULL (not the JSON literal "null") when there were no
	// redactions so non-redaction rows are cleanly distinguishable and the
	// compliance exporters that COALESCE on the column see NULL, not "[]".
	var redactedFieldsArg interface{}
	if len(redactedFields) > 0 {
		if b, mErr := json.Marshal(redactedFields); mErr == nil {
			redactedFieldsArg = b
		} else {
			log.Printf("mcp decision audit: redacted_fields marshal failed (non-fatal): %v", mErr)
		}
	}

	// #2598: correlation_id → first-class column (NULL when unset → singleton),
	// dual-written into policy_details above.
	var correlationIDArg interface{}
	if correlationID != "" {
		correlationIDArg = correlationID
	}

	// #2753: per-session identity → first-class column (NULL when the caller
	// didn't forward X-Session-Id). Read from the request context, stamped in
	// requireMCPAuth, so every writeMCPDecisionAudit call site inherits it
	// without a signature change.
	var sessionIDArg interface{}
	if sid := clientSessionIDFromContext(ctx); sid != "" {
		sessionIDArg = sid
	}

	_, err = db.ExecContext(ctx, `
		INSERT INTO audit_logs (
			id, request_id, timestamp, user_id, user_email, user_role,
			client_id, tenant_id, org_id, request_type, query, query_hash,
			policy_decision, policy_details, decision_id, plane, correlation_id,
			redacted_fields, session_id
		) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19)
	`,
		"audit_mcp_"+decisionID, // id (distinct prefix → no PK collision with audit_/audit_used_/decide_)
		requestID,               // request_id
		time.Now().UTC(),        // timestamp
		userIDInt,               // user_id
		userEmail,               // user_email
		userRole,                // user_role
		clientID,                // client_id
		tenantID,                // tenant_id
		orgID,                   // org_id (nullable)
		requestType,             // request_type — e.g. "mcp_check_output"
		query,                   // query — non-PII descriptor (NEVER raw statement/response)
		queryHash,               // query_hash
		policyDecision,          // policy_decision — canonical past-tense vocab (#2641/#2638)
		detailsJSON,             // policy_details (JSONB)
		decisionID,              // decision_id (first-class column; #2592)
		PlaneMCP,                // plane (#2592)
		correlationIDArg,        // correlation_id (first-class column or NULL; #2598)
		redactedFieldsArg,       // redacted_fields (JSONB array or NULL; #2641)
		sessionIDArg,            // session_id (first-class column or NULL; #2753)
	)
	if err != nil {
		log.Printf("mcp decision audit: insert failed: %v", err)
	}
}

// buildExplainableAuditDetails assembles the policy_details JSONB payload for
// one check-input block row. Pulled out of writeExplainableAuditLog as a PURE
// function so the content contract is pinned by the cross-plane writer/reader
// contract test without a database.
//
// #3243 / v9.16.1: this writer recorded identity ONLY as policy_names +
// policy_matches + policy_versions -- never policy_ids -- while every
// compliance exporter read only policy_details->'policy_ids'->>0, so every
// check-input block rendered a BLANK Policy cell on a regulator artifact (the
// design partner's report). policy_ids is now written additively (the ids of
// the matched policies, in match order) so new rows are uniform with the
// decision/MCP planes; policy_names and policy_matches stay untouched because
// the portal feed and the explain endpoint read them, and because the
// exporters' fallback chain is what heals the PRE-9.16.1 rows on re-export.
func buildExplainableAuditDetails(decisionID, blockReason, topRisk string, matches []RicherPolicyMatch, correlationID string, toolIdentity ...string) map[string]interface{} {
	policyIDs := make([]string, 0, len(matches))
	policyNames := make([]string, 0, len(matches))
	// policy_versions is a parallel { policy_id -> version } map carried at
	// the JSONB top level so explain/SDK consumers can surface the version
	// without unpacking the policy_matches array. Each match's Version is
	// also serialised inline (RicherPolicyMatch.Version → "policy_version"
	// key under each match) — the top-level map is the convenience view
	// used by α3's DecisionExplanation passthrough (#1983).
	policyVersions := make(map[string]int, len(matches))
	for _, m := range matches {
		if m.PolicyID != "" {
			policyIDs = append(policyIDs, m.PolicyID)
		}
		policyNames = append(policyNames, m.PolicyName)
		if m.PolicyID != "" && m.Version > 0 {
			policyVersions[m.PolicyID] = m.Version
		}
	}
	details := map[string]interface{}{
		"decision_id":    decisionID,
		"reason":         blockReason,
		"risk_level":     topRisk,
		"policy_names":   policyNames,
		"policy_matches": matches,
	}
	if len(policyIDs) > 0 {
		details["policy_ids"] = policyIDs
	}
	if len(policyVersions) > 0 {
		details["policy_versions"] = policyVersions
	}
	// #2598: mirror the correlation key into JSONB (read-path resilience) so a
	// check-input block groups with the other stages of the same logical request
	// when the gateway propagates a W3C traceparent.
	if correlationID != "" {
		details["correlation_id"] = correlationID
	}
	// #2904: tool_server/tool_name — same keys the audit_tool_call path already
	// writes, now populated uniformly across every self-auditing policy plane.
	if len(toolIdentity) > 0 && toolIdentity[0] != "" {
		details["tool_server"] = toolIdentity[0]
	}
	if len(toolIdentity) > 1 && toolIdentity[1] != "" {
		details["tool_name"] = toolIdentity[1]
	}
	return details
}

// writeExplainableAuditLog persists a plugin-batch-1-compatible audit_logs
// row for a check-input block. The orchestrator's explain endpoint resolves
// by policy_details->>'decision_id' against audit_logs, so without this
// write `explainDecision(id)` always returns 404 for MCP-path decisions.
//
// The native MCP audit path writes to mcp_query_audits (a separate table)
// for back-compat. Rather than migrate that table + teach explain to union,
// we dual-write a canonical explain-shaped row to audit_logs. audit_logs
// is the source of truth the rest of the decision-record pipeline reads
// from (including override_id search + compliance exports).
//
// Best-effort: any failure logs and returns — the block itself is already
// authoritative, the caller already got the richer response body, and the
// legacy mcp_query_audits entry is written separately and unaffected.
// toolIdentity is variadic — [0]=server, [1]=tool (#2904) — matching
// writeMCPDecisionAudit's convention so unrelated callers don't need updating.
func writeExplainableAuditLog(
	ctx context.Context,
	db *sql.DB,
	decisionID, requestID string,
	tenantID, orgID, clientID, userEmail string,
	userIDStr, userRole string,
	requestType, statement, statementHash, blockReason, topRisk string,
	matches []RicherPolicyMatch,
	correlationID string,
	toolIdentity ...string,
) {
	if db == nil || decisionID == "" {
		return
	}

	// Coerce user_id into an int — audit_logs.user_id is typed that way
	// historically. Non-numeric ids (plugin pseudo-ids, emails) map to 0;
	// the real identity travels via user_email.
	userIDInt := 0
	if n, err := strconv.Atoi(userIDStr); err == nil {
		userIDInt = n
	}

	// ADR-061 / #3329: merge any fincrime attribution recorded on ctx (see
	// writeMCPDecisionAudit above). No-op for every non-fincrime decision.
	detailsJSON, err := json.Marshal(fincrime.MergeAuditDetails(ctx,
		buildExplainableAuditDetails(decisionID, blockReason, topRisk, matches, correlationID, toolIdentity...)))
	if err != nil {
		log.Printf("explainable audit log: marshal failed: %v", err)
		return
	}

	// audit_logs has NOT NULL on user_email, user_role, client_id, tenant_id,
	// request_type, query, query_hash, policy_decision — fall back to
	// placeholders for missing fields rather than hitting NOT NULL errors.
	if userEmail == "" {
		userEmail = "unknown@axonflow.local"
	}
	// RBAC-1 (#2920): honest "unknown" label for a least-privilege MCP caller
	// (RoleNone / ""), consistent with writeMCPDecisionAudit — not a fabricated
	// "user" that collides with a real assigned role.
	if userRole == "" {
		userRole = "unknown"
	}
	if clientID == "" {
		clientID = "unknown"
	}
	if tenantID == "" {
		tenantID = "unknown"
	}
	if statement == "" {
		statement = "(empty statement)"
	}
	if statementHash == "" {
		statementHash = "none"
	}

	// #2592 / ADR-058 Phase 1: dual-write decision_id into the first-class
	// column + stamp plane=mcp (the MCP check-input request plane), alongside
	// the JSONB copy. obligations stays NULL — a check-input block records
	// policy_matches, not an engine-fulfillable obligation.
	// #2598: correlation_id (first-class column or NULL → singleton).
	var correlationIDArg interface{}
	if correlationID != "" {
		correlationIDArg = correlationID
	}
	// #2753: per-session identity → audit_logs.session_id (NULL when the caller
	// didn't forward X-Session-Id). Read from the request context stamped in
	// requireMCPAuth, matching writeMCPDecisionAudit. Static-block check_policy
	// rows are written here, so this is required for session_id parity with the
	// dynamic-block / redact rows.
	var sessionIDArg interface{}
	if sid := clientSessionIDFromContext(ctx); sid != "" {
		sessionIDArg = sid
	}
	_, err = db.ExecContext(ctx, `
		INSERT INTO audit_logs (
			id, request_id, timestamp, user_id, user_email, user_role,
			client_id, tenant_id, org_id, request_type, query, query_hash,
			policy_decision, policy_details, decision_id, plane, correlation_id,
			session_id
		) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
	`,
		"audit_"+decisionID, // id
		requestID,           // request_id
		time.Now().UTC(),    // timestamp
		userIDInt,           // user_id
		userEmail,           // user_email
		userRole,            // user_role
		clientID,            // client_id
		tenantID,            // tenant_id
		orgID,               // org_id
		requestType,         // request_type — e.g. "mcp_check_input"
		statement,           // query
		statementHash,       // query_hash
		// #2641 (AUDIT-C) vocabulary contract (#2638): a check-input/output static
		// block is a "blocked" verdict in the canonical past-tense vocab the portal
		// decisions feed + audit-summary mapping key on — NOT the legacy "deny" this
		// writer used to hardcode, which the audit-summary only mapped to a block by
		// special-case and which the audit-page action filter ('blocked') never
		// matched. All three callers of this writer are static-block paths, so the
		// literal is unconditionally "blocked".
		mcpVerdictBlocked, // policy_decision
		detailsJSON,       // policy_details (JSONB) — decision_id still mirrored here
		decisionID,        // decision_id (first-class column; #2592)
		PlaneMCP,          // plane
		correlationIDArg,  // correlation_id (#2598)
		sessionIDArg,      // session_id (#2753)
	)
	if err != nil {
		log.Printf("explainable audit log: insert failed: %v", err)
	}
}
