// Copyright 2025 AxonFlow
// SPDX-License-Identifier: BUSL-1.1

package agent

import (
	"context"
	"database/sql"
	"encoding/json"
	"log"
	"strconv"
	"time"

	sharedpolicy "axonflow/platform/shared/policy"
)

// buildRicherCheckInputBlock assembles the Plugin Batch 1 fields that extend
// MCPCheckInputResponse on a block: policy_matches (with risk_level +
// allow_override), the top-level risk_level taken from the first overridable
// match (or the first match if none are overridable), and override_available
// plus override_existing_id so the plugin can render a "press this to
// unblock" affordance.
//
// The decision_id is generated by the caller so it can be written into the
// audit entry before this helper runs — the id must survive into
// audit_logs.policy_details so the explain endpoint can resolve it later.
//
// The helper is best-effort. Any DB failure (SQL error, missing column,
// etc.) logs and returns zero values — the block itself is already
// authoritative, so we never fail a block because of a lookup error.
func buildRicherCheckInputBlock(
	ctx context.Context,
	db *sql.DB,
	tenantID, userEmail string,
	matched []sharedpolicy.PolicyMatch,
) (matches []RicherPolicyMatch, topRisk string, overrideAvailable *bool, overrideID string) {
	if db == nil || len(matched) == 0 {
		return nil, "", nil, ""
	}

	matches = make([]RicherPolicyMatch, 0, len(matched))
	var firstOverridablePolicyID string
	for _, m := range matched {
		risk, allowOverride, err := lookupPolicyRiskOverride(ctx, db, m.PolicyID)
		if err != nil {
			log.Printf("richer context: policy lookup failed for %s: %v", m.PolicyID, err)
			// Emit a stub entry so the plugin sees it was matched even when
			// we can't resolve the override flag.
			matches = append(matches, RicherPolicyMatch{
				PolicyID:   m.PolicyID,
				PolicyName: m.PolicyName,
			})
			continue
		}
		matches = append(matches, RicherPolicyMatch{
			PolicyID:      m.PolicyID,
			PolicyName:    m.PolicyName,
			RiskLevel:     risk,
			AllowOverride: allowOverride,
		})
		// Top-level risk_level: prefer first overridable non-critical match
		// so the plugin UI can default to showing the "request override"
		// CTA. Fall back to the first match if none overridable.
		if topRisk == "" || (firstOverridablePolicyID == "" && allowOverride && risk != "critical") {
			topRisk = risk
			if allowOverride && risk != "critical" {
				firstOverridablePolicyID = m.PolicyID
			}
		}
	}

	// override_available + override_existing_id: scoped to
	// (tenant, user, first overridable policy). Critical-risk policies never
	// qualify — the DB trigger guarantees this but we belt-and-suspenders
	// here so the plugin doesn't render an "override" button for something
	// that will 403 anyway.
	if firstOverridablePolicyID == "" || userEmail == "" {
		return matches, topRisk, nil, ""
	}

	available := false
	overrideAvailable = &available

	activeID, found, err := lookupActiveOverride(ctx, db, tenantID, userEmail, firstOverridablePolicyID)
	if err != nil {
		log.Printf("richer context: active-override lookup failed for %s: %v",
			firstOverridablePolicyID, err)
		return matches, topRisk, overrideAvailable, ""
	}
	if found {
		overrideID = activeID
	}
	// allow_override=true + non-critical means the user COULD create an
	// override — so override_available is true regardless of whether one
	// is already active. The plugin distinguishes the two via
	// override_existing_id being set.
	*overrideAvailable = true
	return matches, topRisk, overrideAvailable, overrideID
}

// lookupPolicyRiskOverride fetches risk_level + allow_override for a
// policy. Returns ("", false, nil) if the policy isn't in the table
// (non-fatal — dynamic policies don't live in static_policies).
func lookupPolicyRiskOverride(ctx context.Context, db *sql.DB, policyID string) (string, bool, error) {
	var risk sql.NullString
	var allowOverride sql.NullBool
	err := db.QueryRowContext(ctx, `
		SELECT risk_level, allow_override
		FROM static_policies
		WHERE policy_id = $1
		LIMIT 1
	`, policyID).Scan(&risk, &allowOverride)
	if err == sql.ErrNoRows {
		return "", false, nil
	}
	if err != nil {
		return "", false, err
	}
	return risk.String, allowOverride.Bool, nil
}

// lookupActiveOverride returns (id, true, nil) when the caller already has
// a live (non-revoked, non-expired) override on the policy, or ("",
// false, nil) otherwise. Scoped to (tenant, user, policy). The tool_signature
// dimension is explicitly ignored — on the /api/v1/mcp/check-input path
// there's no canonical "tool" identity, so we check for any override on
// the policy rather than tool-scoped ones.
//
// Accepts either the human-readable policy slug (sys_sqli_admin_bypass) or
// a UUID. policy_overrides.policy_id is UUID-typed; static_policies.policy_id
// is the slug — so a join via static_policies is required when the caller
// passes the slug. We do the join in a single statement so the index on
// static_policies.policy_id stays hot.
func lookupActiveOverride(ctx context.Context, db *sql.DB, tenantID, userEmail, policySlugOrUUID string) (string, bool, error) {
	var id string
	err := db.QueryRowContext(ctx, `
		SELECT po.id
		FROM policy_overrides po
		WHERE po.policy_id = (
		        SELECT sp.id FROM static_policies sp
		        WHERE sp.policy_id = $1
		        LIMIT 1
		      )
		  AND po.created_by = $2
		  AND (po.tenant_id = $3 OR po.tenant_id IS NULL)
		  AND po.revoked_at IS NULL
		  AND (po.expires_at IS NULL OR po.expires_at > NOW())
		ORDER BY po.created_at DESC
		LIMIT 1
	`, policySlugOrUUID, userEmail, tenantID).Scan(&id)
	if err == sql.ErrNoRows {
		return "", false, nil
	}
	if err != nil {
		return "", false, err
	}
	return id, true, nil
}

// applyOverrideToCheckInputBlock applies an active session override to a
// matched-policy block. Returns (true, overrideID) when the block is
// suppressed — caller should treat the request as allowed and emit an
// override_used audit event — or (false, "") when no applicable override
// exists and the block stands.
//
// ADR-044 invariants enforced:
//   - Only non-critical, allow_override=true policies are overridable
//   - Must be scoped to (tenant, user, policy)
//   - Only live overrides (non-revoked, non-expired) qualify
//
// This mirrors orchestrator.ApplyOverrideToResult for the WCP path — the
// same semantics applied to the MCP check-input path so the plugin and
// SDK see consistent behavior regardless of which surface fired the
// request.
func applyOverrideToCheckInputBlock(
	ctx context.Context,
	db *sql.DB,
	tenantID, userEmail string,
	matches []RicherPolicyMatch,
) (string, bool) {
	if db == nil || userEmail == "" || len(matches) == 0 {
		return "", false
	}
	for _, m := range matches {
		if m.RiskLevel == "critical" || !m.AllowOverride {
			continue
		}
		id, found, err := lookupActiveOverride(ctx, db, tenantID, userEmail, m.PolicyID)
		if err != nil {
			log.Printf("apply override: lookup failed for %s: %v", m.PolicyID, err)
			continue
		}
		if found {
			return id, true
		}
	}
	return "", false
}

// writeOverrideUsedEvent records an override_used audit event for the MCP
// check-input path. The orchestrator emits matching events for its own
// paths; this keeps the override audit trail consistent across surfaces.
func writeOverrideUsedEvent(
	ctx context.Context,
	db *sql.DB,
	overrideID, decisionID, tenantID, orgID, clientID, userEmail string,
) {
	if db == nil || overrideID == "" {
		return
	}
	details := map[string]interface{}{
		"decision_id": decisionID,
		"override_id": overrideID,
		"event_type":  "override_used",
	}
	detailsJSON, err := json.Marshal(details)
	if err != nil {
		return
	}
	if userEmail == "" {
		userEmail = "unknown@axonflow.local"
	}
	if clientID == "" {
		clientID = "unknown"
	}
	if tenantID == "" {
		tenantID = "unknown"
	}
	_, _ = db.ExecContext(ctx, `
		INSERT INTO audit_logs (
			id, request_id, timestamp, user_id, user_email, user_role,
			client_id, tenant_id, org_id, request_type, query, query_hash,
			policy_decision, policy_details
		) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
	`,
		"audit_used_"+decisionID,
		decisionID,
		time.Now().UTC(),
		0,
		userEmail,
		"user",
		clientID,
		tenantID,
		orgID,
		"override_used",
		"override applied",
		"none",
		"allow",
		detailsJSON,
	)
}

// writeExplainableAuditLog persists a plugin-batch-1-compatible audit_logs
// row for a check-input block. The orchestrator's explain endpoint resolves
// by policy_details->>'decision_id' against audit_logs, so without this
// write `explainDecision(id)` always returns 404 for MCP-path decisions.
//
// The native MCP audit path writes to mcp_query_audits (a separate table)
// for back-compat. Rather than migrate that table + teach explain to union,
// we dual-write a canonical explain-shaped row to audit_logs. audit_logs
// is the source of truth the rest of the decision-record pipeline reads
// from (including override_id search + compliance exports).
//
// Best-effort: any failure logs and returns — the block itself is already
// authoritative, the caller already got the richer response body, and the
// legacy mcp_query_audits entry is written separately and unaffected.
func writeExplainableAuditLog(
	ctx context.Context,
	db *sql.DB,
	decisionID, requestID string,
	tenantID, orgID, clientID, userEmail string,
	userIDStr, userRole string,
	requestType, statement, statementHash, blockReason, topRisk string,
	matches []RicherPolicyMatch,
) {
	if db == nil || decisionID == "" {
		return
	}

	// Coerce user_id into an int — audit_logs.user_id is typed that way
	// historically. Non-numeric ids (plugin pseudo-ids, emails) map to 0;
	// the real identity travels via user_email.
	userIDInt := 0
	if n, err := strconv.Atoi(userIDStr); err == nil {
		userIDInt = n
	}

	policyNames := make([]string, 0, len(matches))
	for _, m := range matches {
		policyNames = append(policyNames, m.PolicyName)
	}
	details := map[string]interface{}{
		"decision_id":    decisionID,
		"reason":         blockReason,
		"risk_level":     topRisk,
		"policy_names":   policyNames,
		"policy_matches": matches,
	}
	detailsJSON, err := json.Marshal(details)
	if err != nil {
		log.Printf("explainable audit log: marshal failed: %v", err)
		return
	}

	// audit_logs has NOT NULL on user_email, user_role, client_id, tenant_id,
	// request_type, query, query_hash, policy_decision — fall back to
	// placeholders for missing fields rather than hitting NOT NULL errors.
	if userEmail == "" {
		userEmail = "unknown@axonflow.local"
	}
	if userRole == "" {
		userRole = "user"
	}
	if clientID == "" {
		clientID = "unknown"
	}
	if tenantID == "" {
		tenantID = "unknown"
	}
	if statement == "" {
		statement = "(empty statement)"
	}
	if statementHash == "" {
		statementHash = "none"
	}

	_, err = db.ExecContext(ctx, `
		INSERT INTO audit_logs (
			id, request_id, timestamp, user_id, user_email, user_role,
			client_id, tenant_id, org_id, request_type, query, query_hash,
			policy_decision, policy_details
		) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
	`,
		"audit_"+decisionID, // id
		requestID,           // request_id
		time.Now().UTC(),    // timestamp
		userIDInt,           // user_id
		userEmail,           // user_email
		userRole,            // user_role
		clientID,            // client_id
		tenantID,            // tenant_id
		orgID,               // org_id
		requestType,         // request_type — e.g. "mcp_check_input"
		statement,           // query
		statementHash,       // query_hash
		"deny",              // policy_decision
		detailsJSON,         // policy_details (JSONB)
	)
	if err != nil {
		log.Printf("explainable audit log: insert failed: %v", err)
	}
}
