// Copyright 2025 AxonFlow
// SPDX-License-Identifier: BUSL-1.1

package agent

import (
	"context"
	"database/sql"
	"encoding/json"
	"log"
	"strconv"
	"time"

	"github.com/lib/pq"

	sharedpolicy "axonflow/platform/shared/policy"
)

// buildRicherCheckInputBlock assembles the Plugin Batch 1 fields that extend
// MCPCheckInputResponse on a block: policy_matches (with risk_level +
// allow_override), the top-level risk_level taken from the first overridable
// match (or the first match if none are overridable), and override_available
// plus override_existing_id so the plugin can render a "press this to
// unblock" affordance.
//
// The decision_id is generated by the caller so it can be written into the
// audit entry before this helper runs — the id must survive into
// audit_logs.policy_details so the explain endpoint can resolve it later.
//
// The helper is best-effort. Any DB failure (SQL error, missing column,
// etc.) logs and returns zero values — the block itself is already
// authoritative, so we never fail a block because of a lookup error.
func buildRicherCheckInputBlock(
	ctx context.Context,
	db *sql.DB,
	tenantID, userEmail string,
	matched []sharedpolicy.PolicyMatch,
) (matches []RicherPolicyMatch, topRisk string, overrideAvailable *bool, overrideID string) {
	if db == nil || len(matched) == 0 {
		return nil, "", nil, ""
	}

	matches = make([]RicherPolicyMatch, 0, len(matched))
	var firstOverridablePolicyID string
	for _, m := range matched {
		risk, allowOverride, version, err := lookupPolicyMeta(ctx, db, m.PolicyID)
		if err != nil {
			log.Printf("richer context: policy lookup failed for %s: %v", m.PolicyID, err)
			// Emit a stub entry so the plugin sees it was matched even when
			// we can't resolve the override flag.
			matches = append(matches, RicherPolicyMatch{
				PolicyID:   m.PolicyID,
				PolicyName: m.PolicyName,
			})
			continue
		}
		matches = append(matches, RicherPolicyMatch{
			PolicyID:      m.PolicyID,
			PolicyName:    m.PolicyName,
			RiskLevel:     risk,
			AllowOverride: allowOverride,
			Version:       version,
		})
		// Top-level risk_level: prefer first overridable non-critical match
		// so the plugin UI can default to showing the "request override"
		// CTA. Fall back to the first match if none overridable.
		if topRisk == "" || (firstOverridablePolicyID == "" && allowOverride && risk != "critical") {
			topRisk = risk
			if allowOverride && risk != "critical" {
				firstOverridablePolicyID = m.PolicyID
			}
		}
	}

	// override_available + override_existing_id: scoped to
	// (tenant, user, first overridable policy). Critical-risk policies never
	// qualify — the DB trigger guarantees this but we belt-and-suspenders
	// here so the plugin doesn't render an "override" button for something
	// that will 403 anyway.
	if firstOverridablePolicyID == "" || userEmail == "" {
		return matches, topRisk, nil, ""
	}

	available := false
	overrideAvailable = &available

	activeID, found, err := lookupActiveOverride(ctx, db, tenantID, userEmail, firstOverridablePolicyID)
	if err != nil {
		log.Printf("richer context: active-override lookup failed for %s: %v",
			firstOverridablePolicyID, err)
		return matches, topRisk, overrideAvailable, ""
	}
	if found {
		overrideID = activeID
	}
	// allow_override=true + non-critical means the user COULD create an
	// override — so override_available is true regardless of whether one
	// is already active. The plugin distinguishes the two via
	// override_existing_id being set.
	*overrideAvailable = true
	return matches, topRisk, overrideAvailable, overrideID
}

// lookupPolicyMeta fetches risk_level + allow_override + version for a
// policy. Returns ("", false, 0, nil) if the policy isn't in the table
// (non-fatal — dynamic policies don't live in static_policies).
//
// version is the live `static_policies.version` column (#1983 / α1):
// callers stamp the value into audit_logs.policy_details so the explain
// endpoint can answer "which version evaluated me?" without a separate
// lookup. Forward-only — pre-α1 decisions surface no version.
func lookupPolicyMeta(ctx context.Context, db *sql.DB, policyID string) (string, bool, int, error) {
	var risk sql.NullString
	var allowOverride sql.NullBool
	var version sql.NullInt64
	err := db.QueryRowContext(ctx, `
		SELECT risk_level, allow_override, version
		FROM static_policies
		WHERE policy_id = $1
		LIMIT 1
	`, policyID).Scan(&risk, &allowOverride, &version)
	if err == sql.ErrNoRows {
		return "", false, 0, nil
	}
	if err != nil {
		return "", false, 0, err
	}
	return risk.String, allowOverride.Bool, int(version.Int64), nil
}

// collectPolicyVersions distills RicherPolicyMatch.Version values into the
// { policy_id → version } map shape carried by MCPQueryAuditEntry +
// audit_logs.policy_details JSONB (#1983 / α1). Returns nil when no match
// has a known version so audit consumers see omitempty rather than `{}`.
func collectPolicyVersions(matches []RicherPolicyMatch) map[string]int {
	if len(matches) == 0 {
		return nil
	}
	out := make(map[string]int, len(matches))
	for _, m := range matches {
		if m.PolicyID != "" && m.Version > 0 {
			out[m.PolicyID] = m.Version
		}
	}
	if len(out) == 0 {
		return nil
	}
	return out
}

// lookupPolicyVersionsByID returns version numbers keyed by policy_id for the
// given list. Used by the check-output handler to attach policy_version to
// audit entries when static-policy matches fire (#1983 / α1). Single round
// trip via ANY($1::text[]); missing policies (dynamic, ad-hoc) simply don't
// appear in the result map. Best-effort — DB errors return an empty map and
// the audit write proceeds without policy_versions rather than failing the
// decision.
func lookupPolicyVersionsByID(ctx context.Context, db *sql.DB, policyIDs []string) map[string]int {
	if db == nil || len(policyIDs) == 0 {
		return nil
	}
	rows, err := db.QueryContext(ctx, `
		SELECT policy_id, version
		FROM static_policies
		WHERE policy_id = ANY($1)
	`, pq.Array(policyIDs))
	if err != nil {
		log.Printf("richer context: policy_versions batch lookup failed: %v", err)
		return nil
	}
	defer func() { _ = rows.Close() }()

	out := make(map[string]int, len(policyIDs))
	for rows.Next() {
		var pid string
		var ver sql.NullInt64
		if err := rows.Scan(&pid, &ver); err != nil {
			log.Printf("richer context: policy_versions row scan failed: %v", err)
			continue
		}
		if ver.Valid {
			out[pid] = int(ver.Int64)
		}
	}
	if err := rows.Err(); err != nil {
		log.Printf("richer context: policy_versions iteration failed: %v", err)
	}
	if len(out) == 0 {
		return nil
	}
	return out
}

// lookupActiveOverride returns (id, true, nil) when the caller already has
// a live (non-revoked, non-expired) override on the policy, or ("",
// false, nil) otherwise. Scoped to (tenant, user, policy). The tool_signature
// dimension is explicitly ignored — on the /api/v1/mcp/check-input path
// there's no canonical "tool" identity, so we check for any override on
// the policy rather than tool-scoped ones.
//
// Accepts either the human-readable policy slug (sys_sqli_admin_bypass) or
// a UUID. policy_overrides.policy_id is UUID-typed; static_policies.policy_id
// is the slug — so a join via static_policies is required when the caller
// passes the slug. We do the join in a single statement so the index on
// static_policies.policy_id stays hot.
func lookupActiveOverride(ctx context.Context, db *sql.DB, tenantID, userEmail, policySlugOrUUID string) (string, bool, error) {
	var id string
	err := db.QueryRowContext(ctx, `
		SELECT po.id
		FROM policy_overrides po
		WHERE po.policy_id = (
		        SELECT sp.id FROM static_policies sp
		        WHERE sp.policy_id = $1
		        LIMIT 1
		      )
		  AND po.created_by = $2
		  AND (po.tenant_id = $3 OR po.tenant_id IS NULL)
		  AND po.revoked_at IS NULL
		  AND (po.expires_at IS NULL OR po.expires_at > NOW())
		ORDER BY po.created_at DESC
		LIMIT 1
	`, policySlugOrUUID, userEmail, tenantID).Scan(&id)
	if err == sql.ErrNoRows {
		return "", false, nil
	}
	if err != nil {
		return "", false, err
	}
	return id, true, nil
}

// applyOverrideToCheckInputBlock applies an active session override to a
// matched-policy block. Returns (overrideID, &match, true) when the block is
// suppressed — caller should treat the request as allowed and emit an
// override_used audit event — or ("", nil, false) when no applicable
// override exists and the block stands.
//
// The matched RicherPolicyMatch is returned so the caller can stamp the
// overridden policy's version into the override_used audit event
// (#1983 / α1). Returning a pointer keeps the no-override case allocation
// free.
//
// ADR-044 invariants enforced:
//   - Only non-critical, allow_override=true policies are overridable
//   - Must be scoped to (tenant, user, policy)
//   - Only live overrides (non-revoked, non-expired) qualify
//
// This mirrors orchestrator.ApplyOverrideToResult for the WCP path — the
// same semantics applied to the MCP check-input path so the plugin and
// SDK see consistent behavior regardless of which surface fired the
// request.
func applyOverrideToCheckInputBlock(
	ctx context.Context,
	db *sql.DB,
	tenantID, userEmail string,
	matches []RicherPolicyMatch,
) (string, *RicherPolicyMatch, bool) {
	if db == nil || userEmail == "" || len(matches) == 0 {
		return "", nil, false
	}
	for i := range matches {
		m := matches[i]
		if m.RiskLevel == "critical" || !m.AllowOverride {
			continue
		}
		id, found, err := lookupActiveOverride(ctx, db, tenantID, userEmail, m.PolicyID)
		if err != nil {
			log.Printf("apply override: lookup failed for %s: %v", m.PolicyID, err)
			continue
		}
		if found {
			return id, &matches[i], true
		}
	}
	return "", nil, false
}

// writeOverrideUsedEvent records an override_used audit event for the MCP
// check-input path. The orchestrator emits matching events for its own
// paths; this keeps the override audit trail consistent across surfaces.
//
// policyID + policyVersion identify the policy whose block was unblocked
// by this override (#1983 / α1). They land in policy_details JSONB so the
// explain endpoint can surface "which version of which policy was overridden"
// without re-deriving from the override row. Both are best-effort: empty
// policyID / zero policyVersion are simply omitted from the JSONB so we
// never block an override write on an unknown match.
func writeOverrideUsedEvent(
	ctx context.Context,
	db *sql.DB,
	overrideID, decisionID, tenantID, orgID, clientID, userEmail string,
	policyID string, policyVersion int,
	correlationID string,
) {
	if db == nil || overrideID == "" {
		return
	}
	details := map[string]interface{}{
		"decision_id": decisionID,
		"override_id": overrideID,
		"event_type":  "override_used",
	}
	if policyID != "" {
		details["policy_id"] = policyID
	}
	if policyVersion > 0 {
		details["policy_version"] = policyVersion
	}
	// #2598: mirror the correlation key into JSONB (read-path resilience) and the
	// first-class column below, so an override applied mid-chain groups with the
	// other stages of the same logical request.
	if correlationID != "" {
		details["correlation_id"] = correlationID
	}
	detailsJSON, err := json.Marshal(details)
	if err != nil {
		return
	}
	if userEmail == "" {
		userEmail = "unknown@axonflow.local"
	}
	if clientID == "" {
		clientID = "unknown"
	}
	if tenantID == "" {
		tenantID = "unknown"
	}
	// #2592 / ADR-058 Phase 1: dual-write decision_id into the first-class
	// column + stamp plane=mcp (this is the MCP check-input override surface),
	// alongside the JSONB copy. No obligations on an override-used event.
	// #2598: correlation_id (first-class column or NULL → singleton).
	var correlationIDArg interface{}
	if correlationID != "" {
		correlationIDArg = correlationID
	}
	_, _ = db.ExecContext(ctx, `
		INSERT INTO audit_logs (
			id, request_id, timestamp, user_id, user_email, user_role,
			client_id, tenant_id, org_id, request_type, query, query_hash,
			policy_decision, policy_details, decision_id, plane, correlation_id
		) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17)
	`,
		"audit_used_"+decisionID,
		decisionID,
		time.Now().UTC(),
		0,
		userEmail,
		"user",
		clientID,
		tenantID,
		orgID,
		"override_used",
		"override applied",
		"none",
		"allow",
		detailsJSON,
		decisionID,       // decision_id (first-class column)
		PlaneMCP,         // plane
		correlationIDArg, // correlation_id (#2598)
	)
}

// writeExplainableAuditLog persists a plugin-batch-1-compatible audit_logs
// row for a check-input block. The orchestrator's explain endpoint resolves
// by policy_details->>'decision_id' against audit_logs, so without this
// write `explainDecision(id)` always returns 404 for MCP-path decisions.
//
// The native MCP audit path writes to mcp_query_audits (a separate table)
// for back-compat. Rather than migrate that table + teach explain to union,
// we dual-write a canonical explain-shaped row to audit_logs. audit_logs
// is the source of truth the rest of the decision-record pipeline reads
// from (including override_id search + compliance exports).
//
// Best-effort: any failure logs and returns — the block itself is already
// authoritative, the caller already got the richer response body, and the
// legacy mcp_query_audits entry is written separately and unaffected.
func writeExplainableAuditLog(
	ctx context.Context,
	db *sql.DB,
	decisionID, requestID string,
	tenantID, orgID, clientID, userEmail string,
	userIDStr, userRole string,
	requestType, statement, statementHash, blockReason, topRisk string,
	matches []RicherPolicyMatch,
	correlationID string,
) {
	if db == nil || decisionID == "" {
		return
	}

	// Coerce user_id into an int — audit_logs.user_id is typed that way
	// historically. Non-numeric ids (plugin pseudo-ids, emails) map to 0;
	// the real identity travels via user_email.
	userIDInt := 0
	if n, err := strconv.Atoi(userIDStr); err == nil {
		userIDInt = n
	}

	policyNames := make([]string, 0, len(matches))
	// policy_versions is a parallel { policy_id -> version } map carried at
	// the JSONB top level so explain/SDK consumers can surface the version
	// without unpacking the policy_matches array. Each match's Version is
	// also serialised inline (RicherPolicyMatch.Version → "policy_version"
	// key under each match) — the top-level map is the convenience view
	// used by α3's DecisionExplanation passthrough (#1983).
	policyVersions := make(map[string]int, len(matches))
	for _, m := range matches {
		policyNames = append(policyNames, m.PolicyName)
		if m.PolicyID != "" && m.Version > 0 {
			policyVersions[m.PolicyID] = m.Version
		}
	}
	details := map[string]interface{}{
		"decision_id":    decisionID,
		"reason":         blockReason,
		"risk_level":     topRisk,
		"policy_names":   policyNames,
		"policy_matches": matches,
	}
	if len(policyVersions) > 0 {
		details["policy_versions"] = policyVersions
	}
	// #2598: mirror the correlation key into JSONB (read-path resilience) so a
	// check-input block groups with the other stages of the same logical request
	// when the gateway propagates a W3C traceparent.
	if correlationID != "" {
		details["correlation_id"] = correlationID
	}
	detailsJSON, err := json.Marshal(details)
	if err != nil {
		log.Printf("explainable audit log: marshal failed: %v", err)
		return
	}

	// audit_logs has NOT NULL on user_email, user_role, client_id, tenant_id,
	// request_type, query, query_hash, policy_decision — fall back to
	// placeholders for missing fields rather than hitting NOT NULL errors.
	if userEmail == "" {
		userEmail = "unknown@axonflow.local"
	}
	if userRole == "" {
		userRole = "user"
	}
	if clientID == "" {
		clientID = "unknown"
	}
	if tenantID == "" {
		tenantID = "unknown"
	}
	if statement == "" {
		statement = "(empty statement)"
	}
	if statementHash == "" {
		statementHash = "none"
	}

	// #2592 / ADR-058 Phase 1: dual-write decision_id into the first-class
	// column + stamp plane=mcp (the MCP check-input request plane), alongside
	// the JSONB copy. obligations stays NULL — a check-input block records
	// policy_matches, not an engine-fulfillable obligation.
	// #2598: correlation_id (first-class column or NULL → singleton).
	var correlationIDArg interface{}
	if correlationID != "" {
		correlationIDArg = correlationID
	}
	_, err = db.ExecContext(ctx, `
		INSERT INTO audit_logs (
			id, request_id, timestamp, user_id, user_email, user_role,
			client_id, tenant_id, org_id, request_type, query, query_hash,
			policy_decision, policy_details, decision_id, plane, correlation_id
		) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17)
	`,
		"audit_"+decisionID, // id
		requestID,           // request_id
		time.Now().UTC(),    // timestamp
		userIDInt,           // user_id
		userEmail,           // user_email
		userRole,            // user_role
		clientID,            // client_id
		tenantID,            // tenant_id
		orgID,               // org_id
		requestType,         // request_type — e.g. "mcp_check_input"
		statement,           // query
		statementHash,       // query_hash
		"deny",              // policy_decision
		detailsJSON,         // policy_details (JSONB) — decision_id still mirrored here
		decisionID,          // decision_id (first-class column; #2592)
		PlaneMCP,            // plane
		correlationIDArg,    // correlation_id (#2598)
	)
	if err != nil {
		log.Printf("explainable audit log: insert failed: %v", err)
	}
}
