-- Copyright 2025 AxonFlow
-- SPDX-License-Identifier: BUSL-1.1
--
-- Migration: 037_plans
-- Description: Add plans table for Multi-Agent Planning (MAP) two-step execution
-- Related: PR #927 - Support separate GeneratePlan and ExecutePlan operations
--
-- Design:
-- - GeneratePlan stores the workflow definition without executing
-- - ExecutePlan retrieves and executes the stored plan
-- - Plans expire after 1 hour (configurable via expires_at)

-- Plans table - stores generated workflow plans for deferred execution
CREATE TABLE IF NOT EXISTS plans (
    plan_id VARCHAR(255) PRIMARY KEY,

    -- Original request data
    query TEXT NOT NULL,
    domain VARCHAR(100) NOT NULL DEFAULT 'generic',
    execution_mode VARCHAR(50) NOT NULL DEFAULT 'auto',

    -- Workflow definition (JSON)
    workflow_definition JSONB NOT NULL,

    -- Plan metadata
    complexity INTEGER DEFAULT 1,
    parallel BOOLEAN DEFAULT false,
    estimated_duration VARCHAR(50),
    step_count INTEGER NOT NULL DEFAULT 0,

    -- Execution state
    status VARCHAR(50) NOT NULL DEFAULT 'pending',  -- pending, executing, completed, failed, expired
    executed_at TIMESTAMP WITH TIME ZONE,
    execution_result JSONB,
    error_message TEXT,

    -- Multi-tenancy
    org_id VARCHAR(255),
    tenant_id VARCHAR(255),
    user_id VARCHAR(255),
    client_id VARCHAR(255),

    -- TTL management
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,

    -- Timestamps
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Indexes for common queries
CREATE INDEX IF NOT EXISTS idx_plans_status ON plans(status);
CREATE INDEX IF NOT EXISTS idx_plans_org ON plans(org_id);
CREATE INDEX IF NOT EXISTS idx_plans_tenant ON plans(tenant_id);
CREATE INDEX IF NOT EXISTS idx_plans_expires ON plans(expires_at);
CREATE INDEX IF NOT EXISTS idx_plans_created ON plans(created_at);

-- Function to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_plans_timestamp()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to auto-update timestamp
DROP TRIGGER IF EXISTS trigger_update_plans_timestamp ON plans;
CREATE TRIGGER trigger_update_plans_timestamp
    BEFORE UPDATE ON plans
    FOR EACH ROW
    EXECUTE FUNCTION update_plans_timestamp();

-- Function to clean up expired plans (can be called by cron or application)
CREATE OR REPLACE FUNCTION cleanup_expired_plans()
RETURNS INTEGER AS $$
DECLARE
    deleted_count INTEGER;
BEGIN
    DELETE FROM plans
    WHERE expires_at < CURRENT_TIMESTAMP
    AND status IN ('pending', 'expired');

    GET DIAGNOSTICS deleted_count = ROW_COUNT;
    RETURN deleted_count;
END;
$$ LANGUAGE plpgsql;

-- Comments for documentation
COMMENT ON TABLE plans IS 'Stores generated multi-agent plans for deferred execution (MAP two-step flow)';
COMMENT ON COLUMN plans.plan_id IS 'Unique plan identifier returned to client';
COMMENT ON COLUMN plans.workflow_definition IS 'JSON workflow definition generated by PlanningEngine';
COMMENT ON COLUMN plans.status IS 'Plan lifecycle: pending -> executing -> completed/failed, or pending -> expired';
COMMENT ON COLUMN plans.expires_at IS 'Plans expire after 1 hour by default to prevent stale execution';
COMMENT ON FUNCTION cleanup_expired_plans() IS 'Call periodically to remove expired plans';

-- Log migration
DO $$
BEGIN
    RAISE NOTICE 'Migration 037: Created plans table for MAP two-step execution';
END $$;
