//go:build enterprise

// Copyright 2025 AxonFlow
// SPDX-License-Identifier: BUSL-1.1
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package license

import (
	"context"
	"crypto/ed25519"
	"crypto/sha256"
	"encoding/base64"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"strings"
	"sync"
	"time"
)

// License validation for AxonFlow Agent
// Uses Ed25519 asymmetric signatures (see ADR-032)
// Supports offline validation only (public key embedded in binary)

const (
	// License server endpoint (future implementation)
	LicenseServerURL = "https://license.getaxonflow.com/v1/validate"

	// Grace period after license expiry
	GracePeriodDays = 7
)

// Ed25519 public keys for license signature verification.
// These are embedded in the binary — the corresponding private keys
// never leave our infrastructure (AWS Secrets Manager / CF Worker).
//
// The evaluation key is unchanged from the 2026-02-09 generation.
// The enterprise key was rotated on 2026-04-09 as part of issue #1541
// after the previous private seed was found embedded in setup-e2e-testing.sh.
// All active licenses were re-signed under the new key as part of the rotation.

// evaluationPublicKey verifies Evaluation tier licenses.
// Generated by scripts/generate-license-keypair.sh on 2026-02-09.
var evaluationPublicKey = ed25519.PublicKey{
	0x99, 0xbe, 0xd4, 0xd7, 0xa2, 0x50, 0xd8, 0xa0,
	0x8b, 0x2a, 0x79, 0x71, 0x4f, 0x52, 0xf0, 0x59,
	0xd5, 0x79, 0xa0, 0x7a, 0xf8, 0x16, 0x3f, 0x3e,
	0x85, 0x4f, 0x4b, 0x5e, 0x7f, 0xf6, 0x2a, 0x85,
}

// enterprisePublicKey verifies Professional, Enterprise, and Plus tier licenses.
// Rotated on 2026-04-09 (issue #1541). The previous public key (first 8 bytes
// 9a b6 f6 b2) is no longer trusted by this binary.
var enterprisePublicKey = ed25519.PublicKey{
	0x48, 0xac, 0xd8, 0xd1, 0x32, 0xaf, 0x9d, 0x4f,
	0xef, 0x3e, 0x6a, 0x92, 0x49, 0xb6, 0xdb, 0x2f,
	0xe8, 0x07, 0x21, 0x45, 0xd2, 0xaf, 0x2c, 0xfb,
	0x42, 0xb8, 0xc7, 0x22, 0x1e, 0x04, 0xa4, 0xb6,
}

// ValidateHMACSecretAtStartup is a no-op — HMAC is no longer used.
// Kept for interface compatibility during migration. Will be removed.
func ValidateHMACSecretAtStartup() error {
	return nil
}

// Tier represents the license tier
type Tier string

const (
	TierEvaluation     Tier = "Evaluation" // Evaluation tier - free, 90-day limit
	TierProfessional   Tier = "Professional"
	TierEnterprise     Tier = "Enterprise"
	TierEnterprisePlus Tier = "Plus"
	TierCommunity      Tier = "Community" // Community tier - no license required

	// SaaS Plugin product line — orthogonal to the self-hosted tier ladder
	// above (Community/Evaluation/Professional/Enterprise/Plus). These tiers
	// govern the AxonFlow-hosted SaaS Plugin path (try.getaxonflow.com today).
	// `aud=axonflow.saas.plugin` per ADR-050 §1; tokens are issued by the
	// in-agent Stripe webhook, signed with the plugin-claim Ed25519 key
	// (AXONFLOW_PLUGIN_CLAIMED_SIGNING_KEY), and validated per-request by
	// validateCommunitySaasAuth (NOT at agent boot like the self-hosted tiers).
	// See ADR-049 (rewritten) + ADR-050 + PRD_TENANT_DURABILITY_AND_CLAIM.
	TierFree    Tier = "Free"    // SaaS baseline; applied when no X-License-Token is sent
	TierPro     Tier = "Pro"     // V1 paid product, $9.99 one-time / 90 days
	TierPremium Tier = "Premium" // Reserved for a future expensive higher tier; not sold V1
)

// IsPaidTier returns true if the tier is a SELF-HOSTED paid tier
// (Professional, Enterprise, Plus). SaaS Plugin tiers (Pro, Premium) are
// NOT included here because they're a separate product line — use
// IsSaasPluginTier instead. Existing callers that gate self-hosted
// features on IsPaidTier (LLM provider matrix, MAP plans, HITL approvals,
// EU AI Act templates, etc.) keep their semantics unchanged.
func IsPaidTier(t Tier) bool {
	return t == TierProfessional || t == TierEnterprise || t == TierEnterprisePlus
}

// IsEvaluationOrHigher returns true if the tier is Evaluation or any
// SELF-HOSTED paid tier. SaaS Plugin tiers excluded for the same reason
// as IsPaidTier — different product line, different feature surface.
func IsEvaluationOrHigher(t Tier) bool {
	return t == TierEvaluation || IsPaidTier(t)
}

// IsSaasPluginTier returns true if the tier belongs to the SaaS Plugin
// product line that ships paid tokens (Pro, Premium). TierFree is excluded
// because Free is the absence-of-token baseline, never carried in a token's
// payload.
//
// Used by validators (axonflow.saas.plugin accept list) and by the Stripe
// webhook to gate which tier values are valid for issuance.
func IsSaasPluginTier(t Tier) bool {
	return t == TierPro || t == TierPremium
}

// IsPluginTier is the legacy name for IsSaasPluginTier; kept as a thin
// alias so call sites that haven't migrated to the new name still compile.
// New code should call IsSaasPluginTier directly.
func IsPluginTier(t Tier) bool {
	return IsSaasPluginTier(t)
}

// tierRank returns the numeric rank of a tier for comparison.
//
// Returns -1 sentinel for:
//   - SaaS Plugin tiers (Free, Pro, Premium — orthogonal to the self-hosted
//     ladder per ADR-050 §1)
//   - Any unknown / unrecognized tier (defense against forgetting to update
//     this switch when a new tier is added — silent default-zero would have
//     made unknown tiers compare equal to Community, a footgun that GAP-3
//     specifically called out)
//
// Callers comparing ranks (TierSatisfiesRequirement, customer-portal admin)
// MUST treat -1 as "not comparable / fail closed" — see
// TierSatisfiesRequirement below for the canonical handling.
func tierRank(t Tier) int {
	switch t {
	case TierCommunity:
		return 0
	case TierEvaluation:
		return 0
	case TierProfessional:
		return 1
	case TierEnterprise:
		return 2
	case TierEnterprisePlus:
		return 3
	case TierFree, TierPro, TierPremium:
		return -1 // sentinel: SaaS Plugin tiers are not on the self-hosted ladder
	default:
		// Unknown tier — return -1 so rank-based comparisons fail closed.
		// Pre-GAP-3 this returned 0 (== Community), which silently treated
		// unknown tiers as the lowest valid tier. That meant any future tier
		// added without updating this switch would default to Community
		// rank, opening up cross-tier comparison bugs (e.g. an enterprise
		// admin escalation check evaluating "Unknown >= Community" as true).
		return -1
	}
}

// TierSatisfiesRequirement returns true if the current tier meets or exceeds
// the required tier level. Used for provider access gating.
//
// Fails closed when EITHER tier has rank -1 (SaaS Plugin tiers — orthogonal
// to the self-hosted ladder per ADR-050 §1 — OR unknown tiers). Pre-GAP-3
// the raw `>=` comparison treated -1 against any positive rank as false,
// but treated -1 against -1 as TRUE (-1 >= -1 → unknown satisfies unknown),
// and treated 0 against -1 as TRUE (Community satisfies plugin-claim) —
// both were wrong. The explicit -1 check makes the orthogonality intent
// enforceable rather than incidental.
func TierSatisfiesRequirement(current, required Tier) bool {
	cr := tierRank(current)
	rr := tierRank(required)
	if cr < 0 || rr < 0 {
		return false
	}
	return cr >= rr
}

// normalizeTier validates that a tier string matches one of the canonical
// Tier constants. Returns the tier as-is if valid, or Tier(raw) for unknown
// values (which will fail downstream validation).
func normalizeTier(raw string) Tier {
	switch raw {
	case string(TierProfessional):
		return TierProfessional
	case string(TierEnterprise):
		return TierEnterprise
	case string(TierEnterprisePlus):
		return TierEnterprisePlus
	case string(TierEvaluation):
		return TierEvaluation
	default:
		return Tier(raw)
	}
}

// ValidationResult contains the result of license validation
type ValidationResult struct {
	Valid bool
	Tier  Tier
	// DeploymentID is the v9 name for the deployment/licensee identity that
	// the agent validates against the ORG_ID env var at startup. Per ADR-052
	// §3 + ADR-054 this is NOT the customer row org_id — it identifies the
	// AxonFlow installation/license owner (e.g. "axonflow-community-saas").
	// Populated from the V3 `deployment_id` payload field if present, else
	// from the legacy V2 `org_id` field. Use LicenseDeploymentID() to read.
	DeploymentID string
	// OrgID is the V2 license field name and equals DeploymentID for
	// backward compatibility. Retained during the v9 window so existing
	// call sites that read validationResult.OrgID keep compiling. New code
	// MUST call LicenseDeploymentID() to make the semantic explicit.
	// Removal in v10.
	//
	// Deprecated: use LicenseDeploymentID() instead.
	OrgID           string
	MaxNodes        int
	ExpiresAt       time.Time
	DaysUntilExpiry int
	GracePeriodDays int
	Error           string
	Message         string
	Features        map[string]bool
	Limits          TierLimits // Tier-specific resource limits

	// Service identity fields (optional - only for service licenses)
	ServiceName string   `json:"service_name,omitempty"` // e.g., "trip-planner"
	ServiceType string   `json:"service_type,omitempty"` // "client-application", "backend-service", "integration"
	Permissions []string `json:"permissions,omitempty"`  // e.g., ["mcp:amadeus:search_flights"]
	Email       string   `json:"email,omitempty"`
	LicenseID   string   `json:"license_id,omitempty"`
}

// LicenseDeploymentID returns the deployment/licensee identity for this
// validated license. Per ADR-052 §3 + ADR-054 this is the AxonFlow
// installation/license owner — used for startup validation against ORG_ID
// only and MUST NOT be written into customer-data rows (use the
// auth-derived request OrgID for that).
//
// Prefers the V3 `deployment_id` field; falls back to the V2 `org_id`
// field for legacy licenses. Always non-empty for a valid result.
func (r *ValidationResult) LicenseDeploymentID() string {
	if r.DeploymentID != "" {
		return r.DeploymentID
	}
	return r.OrgID
}

// ValidateLicense validates an AxonFlow license key.
// Supports the Ed25519-signed format: AXON-{PAYLOAD}.{SIGNATURE}
// Rejects old V2 (HMAC) and V1 formats with a clear error.
func ValidateLicense(ctx context.Context, licenseKey string) (*ValidationResult, error) {
	if licenseKey == "" {
		// No license key = Community tier (matches community build behavior)
		return &ValidationResult{
			Valid:    true,
			Tier:     TierCommunity,
			Features: getFeatures(TierCommunity),
			Limits:   CommunityLimits,
		}, nil
	}

	// Check cache first
	if cached := getCachedValidation(licenseKey); cached != nil {
		return cached, nil
	}

	// Try offline validation (fastest, only method currently)
	result, err := validateOffline(licenseKey)
	if err != nil {
		return nil, fmt.Errorf("license validation failed: %w", err)
	}

	// Cache the validation result
	cacheValidation(licenseKey, result)

	return result, nil
}

// ServiceLicensePayload represents the JSON payload in an Ed25519-signed license.
//
// W4 plugin-claim additions (TenantID, Aud, JTI, KID, Origin) are all
// `omitempty` so they only appear in plugin-claim tokens. Self-hosted
// (Evaluation/Professional/Enterprise/Plus) tokens continue to serialize
// without these fields, preserving backward compatibility — existing
// validators don't read fields they don't know about.
type ServiceLicensePayload struct {
	LicenseID string `json:"id,omitempty"` // Unique license ID
	Tier      string `json:"tier"`
	// DeploymentID is the v9 (V3 license payload) field name for the
	// deployment/licensee identity per ADR-052 §3 + ADR-054. New licenses
	// minted by GenerateServiceLicenseKey* populate BOTH this field and
	// the legacy `org_id` field (with the same value) so V2-only readers
	// keep validating signed payloads they wrote pre-v9. When both fields
	// are present, validateEd25519License prefers `deployment_id`.
	DeploymentID string      `json:"deployment_id,omitempty"`
	OrgID        string      `json:"org_id"`
	ServiceName  string      `json:"service_name,omitempty"`
	ServiceType  string      `json:"service_type,omitempty"`
	Permissions  []string    `json:"permissions,omitempty"`
	IssuedAt     string      `json:"issued_at,omitempty"` // Format: YYYYMMDD
	ExpiresAt    string      `json:"expires_at"`          // Format: YYYYMMDD
	Email        string      `json:"email,omitempty"`
	Email2       string      `json:"email2,omitempty"`
	Limits       *TierLimits `json:"limits,omitempty"`

	// W4 plugin-claim claims (per ADR-049 sections 1, 9). Only present in
	// plugin-claim tokens. Validated by agent middleware on each request.
	TenantID string `json:"tenant_id,omitempty"` // cs_<uuid> binding the token to a community-saas tenant
	Aud      string `json:"aud,omitempty"`       // expected audience: "community_saas_plugin" for plugin-claim
	JTI      string `json:"jti,omitempty"`       // unique token id (UUID v7) for revocation + audit
	KID      string `json:"kid,omitempty"`       // signing key id (e.g., "v3-2026-05-04") for rotation
	Origin   string `json:"origin,omitempty"`    // "plugin" / "self_hosted_eval" / "self_hosted_enterprise" — for cross-context check
}

// =============================================================================
// ADR-050 license matrix: per-context validators
// =============================================================================
//
// The canonical aud constants + HostingMode/HasScope helpers + the SaaS
// Plugin path accept list live in scope.go (no build tag). This file
// owns the SDK / Self-Hosted accept lists + the per-context validator
// wrappers used by the enterprise-build call sites.

// ExpectedPluginClaimAudience aliases scope.go's AudSaaSPlugin so legacy
// callers that still reference `ExpectedPluginClaimAudience` keep
// compiling without a rename pass.
const ExpectedPluginClaimAudience = AudSaaSPlugin

// ExpectedPluginClaimOrigin is the deprecated `origin` field used by the
// abandoned parallel-JSONB design. ADR-050 §2 dropped it as redundant with
// the third `aud` segment. The constant remains for any caller that still
// references it (no-op after the validator stopped reading it on
// 2026-05-05); new code SHOULD NOT set or check this field.
//
// Deprecated: use the `aud` claim and `HasScope` instead.
const ExpectedPluginClaimOrigin = "plugin"

// saasSDKPathAcceptList is the closed set of aud values accepted by the
// SaaS SDK path validator. Reserved for the future SaaS SDK product —
// shipped day one so future product launches are config + marketing only,
// not architecture work. (The SaaS Plugin path's accept list lives in
// scope.go as `SaaSPluginPathAcceptList`.)
var saasSDKPathAcceptList = []string{AudSaaSSDK, AudSaaSFull}

// selfHostedLicenseAcceptList is the closed set of aud values accepted by
// the self-hosted license loader (AXONFLOW_LICENSE_KEY env var read at
// agent boot). Per ADR-050 §3.
var selfHostedLicenseAcceptList = []string{AudSelfHostedPlugin, AudSelfHostedSDK, AudSelfHostedFull}

// ValidateForSaasPluginPath is the per-context validator for the SaaS
// Plugin path (X-License-Token on requests to the SaaS agent). Delegates
// to `IsSaaSPluginPathAud` (scope.go) so the accept list — which includes
// the legacy `community_saas_plugin` aud for W4 scaffolding tokens — is
// the single source of truth.
//
// Caller responsibilities (NOT done here): signature verification, expiry
// check, plugin_user_licenses row lookup, tenant_id match.
func ValidateForSaasPluginPath(payload *ServiceLicensePayload) error {
	if !IsSaaSPluginPathAud(payload.Aud) {
		return &PluginClaimValidationError{Reason: fmt.Sprintf(
			"aud %q not accepted by the SaaS Plugin path (need one of %v)",
			payload.Aud, SaaSPluginPathAcceptList)}
	}
	return nil
}

// ValidateForSaasSDKPath is the per-context validator for the SaaS SDK
// path. Reserved for the future SaaS SDK product.
func ValidateForSaasSDKPath(payload *ServiceLicensePayload) error {
	for _, accepted := range saasSDKPathAcceptList {
		if payload.Aud == accepted {
			return nil
		}
	}
	return &PluginClaimValidationError{Reason: fmt.Sprintf(
		"aud %q not accepted by the SaaS SDK path (need one of %v)",
		payload.Aud, saasSDKPathAcceptList)}
}

// ValidateForSelfHostedLicense is the per-context validator for the
// self-hosted license loader (AXONFLOW_LICENSE_KEY env var at agent boot).
// Per ADR-050 §8 missing-aud tokens predate the matrix and are accepted
// (treated as `axonflow.self_hosted.full` equivalents — the only quadrant
// they could plausibly belong to). New tokens MUST carry an explicit aud
// value from selfHostedLicenseAcceptList.
func ValidateForSelfHostedLicense(payload *ServiceLicensePayload) error {
	if payload.Aud == "" {
		// ADR-050 §8 backward-compat: legacy customer tokens with no
		// aud claim were issued for self-hosted use; accept them.
		return nil
	}
	for _, accepted := range selfHostedLicenseAcceptList {
		if payload.Aud == accepted {
			return nil
		}
	}
	return &PluginClaimValidationError{Reason: fmt.Sprintf(
		"aud %q not accepted by the self-hosted license loader (need one of %v)",
		payload.Aud, selfHostedLicenseAcceptList)}
}

// PluginClaimValidationError indicates the token failed a SaaS Plugin
// validation step (audience). Distinct error type so callers can
// distinguish "this is an Ed25519-valid token but not for our context"
// from "this token's signature doesn't verify".
type PluginClaimValidationError struct {
	Reason string
}

func (e *PluginClaimValidationError) Error() string {
	return "SaaS Plugin validation failed: " + e.Reason
}

// validateEd25519License validates an Ed25519-signed license key.
// Format: AXON-{BASE64URL(JSON_PAYLOAD)}.{BASE64URL(ED25519_SIGNATURE)}
func validateEd25519License(licenseKey string) (*ValidationResult, error) {
	// Strip "AXON-" prefix
	rest := licenseKey[5:]

	// Split on "." — payload.signature
	dotIdx := strings.LastIndex(rest, ".")
	if dotIdx < 1 {
		return nil, errors.New("invalid license format: missing signature separator")
	}

	payloadBase64 := rest[:dotIdx]
	signatureBase64 := rest[dotIdx+1:]

	// Decode payload
	payloadJSON, err := base64.RawURLEncoding.DecodeString(payloadBase64)
	if err != nil {
		return nil, fmt.Errorf("invalid payload encoding: %w", err)
	}

	// Parse JSON payload
	var payload ServiceLicensePayload
	if err := json.Unmarshal(payloadJSON, &payload); err != nil {
		return nil, fmt.Errorf("invalid payload JSON: %w", err)
	}

	// Decode signature
	signature, err := base64.RawURLEncoding.DecodeString(signatureBase64)
	if err != nil {
		return nil, fmt.Errorf("invalid signature encoding: %w", err)
	}

	if len(signature) != ed25519.SignatureSize {
		return nil, fmt.Errorf("invalid signature length: expected %d bytes, got %d", ed25519.SignatureSize, len(signature))
	}

	// Determine tier and select appropriate public key.
	// normalizeTier handles both legacy abbreviations (PRO, ENT, PLUS, EVALUATION)
	// and the canonical full names used in newly issued licenses.
	tier := normalizeTier(payload.Tier)
	if !verifyEd25519Signature([]byte(payloadBase64), signature, tier) {
		return nil, errors.New("invalid license signature")
	}

	// Validate tier
	switch tier {
	case TierEvaluation, TierProfessional, TierEnterprise, TierEnterprisePlus:
		// valid
	default:
		return nil, fmt.Errorf("invalid license tier: %s", tier)
	}

	// Cross-quadrant guard: a self-hosted license loader (this path) MUST
	// reject tokens issued for SaaS quadrants. Per ADR-050 §3 the accept
	// list is `axonflow.self_hosted.{plugin,sdk,full}`. Tokens with empty
	// `aud` predate the rename and fall back to `axonflow.self_hosted.full`
	// (still on the accept list), so legacy customer licenses keep working.
	// A buyer who pastes their `axonflow.saas.plugin` Pro token into
	// AXONFLOW_LICENSE_KEY trips this check and gets a clear boot-time
	// rejection.
	if err := ValidateForSelfHostedLicense(&payload); err != nil {
		return nil, fmt.Errorf("license validation failed: %w", err)
	}

	// Parse expiry date
	expiry, err := time.Parse("20060102", payload.ExpiresAt)
	if err != nil {
		return nil, fmt.Errorf("invalid expiry date format: %w", err)
	}

	// Check expiry
	now := time.Now()
	daysUntilExpiry := int(expiry.Sub(now).Hours() / 24)

	// V3 license payload (ADR-054): prefer `deployment_id` over the legacy
	// `org_id`. New licenses ship both fields with the same value so V2
	// readers still see `org_id`; V3 readers prefer `deployment_id` when
	// it's non-empty. Both ValidationResult.DeploymentID and .OrgID are
	// populated to the resolved identity for backward-compat call sites.
	resolvedDeploymentID := payload.DeploymentID
	if resolvedDeploymentID == "" {
		resolvedDeploymentID = payload.OrgID
	}
	result := &ValidationResult{
		Valid:           true,
		Tier:            tier,
		DeploymentID:    resolvedDeploymentID,
		OrgID:           resolvedDeploymentID,
		ExpiresAt:       expiry,
		DaysUntilExpiry: daysUntilExpiry,
		GracePeriodDays: 0,
		Features:        getFeatures(tier),
		Limits:          GetTierLimits(tier),
		ServiceName:     payload.ServiceName,
		ServiceType:     payload.ServiceType,
		Permissions:     payload.Permissions,
		Email:           payload.Email,
		LicenseID:       payload.LicenseID,
	}

	// Set max nodes based on tier
	switch tier {
	case TierEvaluation:
		result.MaxNodes = 2
	case TierProfessional:
		result.MaxNodes = 10
	case TierEnterprise:
		result.MaxNodes = 50
	case TierEnterprisePlus:
		result.MaxNodes = 9999 // Unlimited
	}

	// Check if expired
	if now.After(expiry) {
		daysExpired := int(now.Sub(expiry).Hours() / 24)

		if daysExpired <= GracePeriodDays {
			result.GracePeriodDays = GracePeriodDays - daysExpired
			result.Message = fmt.Sprintf("License expired %d days ago, %d days of grace period remaining",
				daysExpired, result.GracePeriodDays)
		} else {
			result.Valid = false
			result.Error = "LICENSE_EXPIRED"
			result.Message = fmt.Sprintf("License expired on %s (grace period ended)", expiry.Format("2006-01-02"))
			return result, nil
		}
	}

	// Valid license
	if daysUntilExpiry <= 30 {
		result.Message = fmt.Sprintf("License expires in %d days", daysUntilExpiry)
	}

	return result, nil
}

// verifyEd25519Signature verifies the Ed25519 signature of a license payload.
// Selects the appropriate public key based on the license tier.
func verifyEd25519Signature(payload, signature []byte, tier Tier) bool {
	var pubKey ed25519.PublicKey
	switch tier {
	case TierEvaluation:
		pubKey = evaluationPublicKey
	default: // Professional, Enterprise, Plus
		pubKey = enterprisePublicKey
	}
	return ed25519.Verify(pubKey, payload, signature)
}

// validateOffline validates a license key without calling the license server.
// Only Ed25519-signed format (AXON-{PAYLOAD}.{SIGNATURE}) is supported.
// Old V2 (AXON-V2-...) and V1 (AXON-TIER-...) formats are rejected.
func validateOffline(licenseKey string) (*ValidationResult, error) {
	if !strings.HasPrefix(licenseKey, "AXON-") {
		return nil, errors.New("invalid license key prefix (expected AXON-)")
	}

	// Reject old V2 format
	if strings.HasPrefix(licenseKey, "AXON-V2-") {
		return nil, errors.New("V2 license format (AXON-V2-...) is no longer supported. " +
			"Please request a new license at https://getaxonflow.com/evaluation-license")
	}

	// Check for Ed25519 format: must contain "." separator after AXON- prefix
	rest := licenseKey[5:]
	if strings.Contains(rest, ".") {
		return validateEd25519License(licenseKey)
	}

	// V1 format is deprecated
	return nil, errors.New("V1 license format (AXON-TIER-ORG-...) is no longer supported. " +
		"Please request a new license at https://getaxonflow.com/evaluation-license")
}

// getFeatures returns the features enabled for a given tier
func getFeatures(tier Tier) map[string]bool {
	features := make(map[string]bool)

	switch tier {
	case TierEvaluation:
		features["audit_logging"] = true
		features["basic_support"] = true

	case TierProfessional:
		features["multi_tenant"] = false
		features["advanced_policies"] = false
		features["sla_guarantee"] = false
		features["audit_logging"] = true
		features["basic_support"] = true

	case TierEnterprise:
		features["multi_tenant"] = true
		features["advanced_policies"] = true
		features["sla_guarantee"] = true
		features["audit_logging"] = true
		features["priority_support"] = true
		features["custom_connectors"] = true

	case TierEnterprisePlus:
		features["multi_tenant"] = true
		features["advanced_policies"] = true
		features["sla_guarantee"] = true
		features["audit_logging"] = true
		features["24x7_support"] = true
		features["custom_connectors"] = true
		features["dedicated_sa"] = true
		features["unlimited_nodes"] = true
	}

	return features
}

// Thread-safe validation cache with TTL and bounded size.
// Keys are SHA-256 hashes to avoid storing license keys in plaintext.
var (
	validationCache        = make(map[string]*cachedValidation)
	validationCacheMu      sync.RWMutex
	validationCacheTTL     = 5 * time.Minute
	validationCacheMaxSize = 100
)

type cachedValidation struct {
	Result   *ValidationResult
	CachedAt time.Time
}

// getCachedValidation returns a cached result if it exists and is not expired.
func getCachedValidation(licenseKey string) *ValidationResult {
	keyHash := hashLicenseKey(licenseKey)
	validationCacheMu.RLock()
	entry, ok := validationCache[keyHash]
	validationCacheMu.RUnlock()
	if !ok {
		return nil
	}
	if time.Since(entry.CachedAt) > validationCacheTTL {
		validationCacheMu.Lock()
		delete(validationCache, keyHash)
		validationCacheMu.Unlock()
		return nil
	}
	return entry.Result
}

// cacheValidation stores a validation result in cache
func cacheValidation(licenseKey string, result *ValidationResult) {
	keyHash := hashLicenseKey(licenseKey)
	validationCacheMu.Lock()
	defer validationCacheMu.Unlock()
	// Evict oldest entries if cache is full
	if len(validationCache) >= validationCacheMaxSize {
		var oldestKey string
		var oldestTime time.Time
		for k, v := range validationCache {
			if oldestKey == "" || v.CachedAt.Before(oldestTime) {
				oldestKey = k
				oldestTime = v.CachedAt
			}
		}
		delete(validationCache, oldestKey)
	}
	validationCache[keyHash] = &cachedValidation{
		Result:   result,
		CachedAt: time.Now(),
	}
}

func hashLicenseKey(key string) string {
	h := sha256.Sum256([]byte(key))
	return hex.EncodeToString(h[:])
}

// ValidateWithRetry validates a license with automatic retry on transient failures
// This is the recommended function to use at agent startup
func ValidateWithRetry(ctx context.Context, licenseKey string, maxAttempts int) (*ValidationResult, error) {
	var lastErr error

	for attempt := 1; attempt <= maxAttempts; attempt++ {
		result, err := ValidateLicense(ctx, licenseKey)
		if err == nil {
			return result, nil
		}

		lastErr = err

		// Don't retry on permanent failures
		if strings.Contains(err.Error(), "invalid license") ||
			strings.Contains(err.Error(), "expired") ||
			strings.Contains(err.Error(), "no longer supported") {
			return nil, err
		}

		// Exponential backoff for retries
		if attempt < maxAttempts {
			backoff := time.Duration(attempt*attempt) * time.Second
			select {
			case <-ctx.Done():
				return nil, ctx.Err()
			case <-time.After(backoff):
				// Continue to next attempt
			}
		}
	}

	return nil, fmt.Errorf("license validation failed after %d attempts: %w", maxAttempts, lastErr)
}

// IsEnterpriseTier checks if the AXONFLOW_LICENSE_KEY environment variable
// contains a valid Enterprise or EnterprisePlus license.
// This is the canonical way to check for Enterprise license across the codebase.
func IsEnterpriseTier(ctx context.Context) bool {
	licenseKey := os.Getenv("AXONFLOW_LICENSE_KEY")
	if licenseKey == "" {
		return false
	}
	result, err := ValidateLicense(ctx, licenseKey)
	if err != nil || result == nil || !result.Valid {
		return false
	}
	return result.Tier == TierEnterprise || result.Tier == TierEnterprisePlus
}
