//go:build enterprise

// Copyright 2025 AxonFlow
// SPDX-License-Identifier: BUSL-1.1
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package license

import (
	"context"
	"crypto/ed25519"
	"crypto/sha256"
	"encoding/base64"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"strings"
	"sync"
	"time"
)

// License validation for AxonFlow Agent
// Uses Ed25519 asymmetric signatures (see ADR-032)
// Supports offline validation only (public key embedded in binary)

const (
	// License server endpoint (future implementation)
	LicenseServerURL = "https://license.getaxonflow.com/v1/validate"

	// Grace period after license expiry
	GracePeriodDays = 7
)

// Ed25519 public keys for license signature verification.
// These are embedded in the binary — the corresponding private keys
// never leave our infrastructure (AWS Secrets Manager / CF Worker).
//
// The evaluation key is unchanged from the 2026-02-09 generation.
// The enterprise key was rotated on 2026-04-09 as part of issue #1541
// after the previous private seed was found embedded in setup-e2e-testing.sh.
// All active licenses were re-signed under the new key as part of the rotation.

// evaluationPublicKey verifies Evaluation tier licenses.
// Generated by scripts/generate-license-keypair.sh on 2026-02-09.
var evaluationPublicKey = ed25519.PublicKey{
	0x99, 0xbe, 0xd4, 0xd7, 0xa2, 0x50, 0xd8, 0xa0,
	0x8b, 0x2a, 0x79, 0x71, 0x4f, 0x52, 0xf0, 0x59,
	0xd5, 0x79, 0xa0, 0x7a, 0xf8, 0x16, 0x3f, 0x3e,
	0x85, 0x4f, 0x4b, 0x5e, 0x7f, 0xf6, 0x2a, 0x85,
}

// enterprisePublicKey verifies Professional, Enterprise, and Plus tier licenses.
// Rotated on 2026-04-09 (issue #1541). The previous public key (first 8 bytes
// 9a b6 f6 b2) is no longer trusted by this binary.
var enterprisePublicKey = ed25519.PublicKey{
	0x48, 0xac, 0xd8, 0xd1, 0x32, 0xaf, 0x9d, 0x4f,
	0xef, 0x3e, 0x6a, 0x92, 0x49, 0xb6, 0xdb, 0x2f,
	0xe8, 0x07, 0x21, 0x45, 0xd2, 0xaf, 0x2c, 0xfb,
	0x42, 0xb8, 0xc7, 0x22, 0x1e, 0x04, 0xa4, 0xb6,
}

// ValidateHMACSecretAtStartup is a no-op — HMAC is no longer used.
// Kept for interface compatibility during migration. Will be removed.
func ValidateHMACSecretAtStartup() error {
	return nil
}

// Tier represents the license tier
type Tier string

const (
	TierEvaluation     Tier = "Evaluation"    // Evaluation tier - free, 90-day limit
	TierProfessional   Tier = "Professional"
	TierEnterprise     Tier = "Enterprise"
	TierEnterprisePlus Tier = "Plus"
	TierCommunity      Tier = "Community" // Community tier - no license required

	// W4 plugin-claim product line — orthogonal to the self-hosted tier ladder
	// above (Community/Evaluation/Professional/Enterprise/Plus). These tiers
	// are issued by axonflow-billing on Stripe Checkout success, signed with
	// the plugin-claim Ed25519 key (AXONFLOW_PLUGIN_CLAIMED_SIGNING_KEY), and
	// validated per-request by the agent middleware (NOT at orchestrator boot
	// like the self-hosted tiers). See ADR-049 for the full design.
	TierPluginClaimed      Tier = "plugin-claimed"      // Pro v1, $9.99 one-time
	TierPluginSubscription Tier = "plugin-subscription" // Premium v2 placeholder; not issued in v1
)

// IsPaidTier returns true if the tier is a SELF-HOSTED paid tier
// (Professional, Enterprise, Plus). Plugin-claim tiers are NOT included
// here because they're a separate product line — use IsPluginTier instead.
// This preserves backward compatibility with all existing callers that
// gate self-hosted features on IsPaidTier (LLM provider matrix, MAP plans,
// HITL approvals, EU AI Act templates, etc.).
func IsPaidTier(t Tier) bool {
	return t == TierProfessional || t == TierEnterprise || t == TierEnterprisePlus
}

// IsEvaluationOrHigher returns true if the tier is Evaluation or any
// SELF-HOSTED paid tier. Plugin-claim tiers excluded for the same reason
// as IsPaidTier — different product line, different feature surface.
func IsEvaluationOrHigher(t Tier) bool {
	return t == TierEvaluation || IsPaidTier(t)
}

// IsPluginTier returns true if the tier belongs to the plugin-claim
// product line (Pro v1 or future Premium). Plugin tiers are orthogonal
// to the self-hosted tier ladder: they're validated per-request in the
// agent middleware, their entitlements live in plugin_user_licenses DB
// rows (NOT in the token), and they're issued by axonflow-billing on
// Stripe Checkout success.
//
// Use this in agent middleware to branch on plugin-claim vs self-hosted
// validation context. See ADR-049 sections 1, 2, 9.
func IsPluginTier(t Tier) bool {
	return t == TierPluginClaimed || t == TierPluginSubscription
}

// tierRank returns the numeric rank of a tier for comparison.
// Plugin-claim tiers return -1 (intentionally outside the ladder) so any
// rank-based comparison against them yields predictable "not comparable"
// behavior. Plugin-claim is product-orthogonal to self-hosted tiers — they
// don't sit on the same continuum.
func tierRank(t Tier) int {
	switch t {
	case TierCommunity:
		return 0
	case TierEvaluation:
		return 0
	case TierProfessional:
		return 1
	case TierEnterprise:
		return 2
	case TierEnterprisePlus:
		return 3
	case TierPluginClaimed, TierPluginSubscription:
		return -1 // sentinel: not on the self-hosted tier ladder
	default:
		return 0
	}
}

// TierSatisfiesRequirement returns true if the current tier meets or exceeds
// the required tier level. Used for provider access gating.
func TierSatisfiesRequirement(current, required Tier) bool {
	return tierRank(current) >= tierRank(required)
}

// normalizeTier validates that a tier string matches one of the canonical
// Tier constants. Returns the tier as-is if valid, or Tier(raw) for unknown
// values (which will fail downstream validation).
func normalizeTier(raw string) Tier {
	switch raw {
	case string(TierProfessional):
		return TierProfessional
	case string(TierEnterprise):
		return TierEnterprise
	case string(TierEnterprisePlus):
		return TierEnterprisePlus
	case string(TierEvaluation):
		return TierEvaluation
	default:
		return Tier(raw)
	}
}

// ValidationResult contains the result of license validation
type ValidationResult struct {
	Valid           bool
	Tier            Tier
	OrgID           string // Organization ID extracted from license key
	MaxNodes        int
	ExpiresAt       time.Time
	DaysUntilExpiry int
	GracePeriodDays int
	Error           string
	Message         string
	Features        map[string]bool
	Limits          TierLimits // Tier-specific resource limits

	// Service identity fields (optional - only for service licenses)
	ServiceName string   `json:"service_name,omitempty"` // e.g., "trip-planner"
	ServiceType string   `json:"service_type,omitempty"` // "client-application", "backend-service", "integration"
	Permissions []string `json:"permissions,omitempty"`  // e.g., ["mcp:amadeus:search_flights"]
	Email       string   `json:"email,omitempty"`
	LicenseID   string   `json:"license_id,omitempty"`
}

// ValidateLicense validates an AxonFlow license key.
// Supports the Ed25519-signed format: AXON-{PAYLOAD}.{SIGNATURE}
// Rejects old V2 (HMAC) and V1 formats with a clear error.
func ValidateLicense(ctx context.Context, licenseKey string) (*ValidationResult, error) {
	if licenseKey == "" {
		// No license key = Community tier (matches community build behavior)
		return &ValidationResult{
			Valid:    true,
			Tier:     TierCommunity,
			Features: getFeatures(TierCommunity),
			Limits:   CommunityLimits,
		}, nil
	}

	// Check cache first
	if cached := getCachedValidation(licenseKey); cached != nil {
		return cached, nil
	}

	// Try offline validation (fastest, only method currently)
	result, err := validateOffline(licenseKey)
	if err != nil {
		return nil, fmt.Errorf("license validation failed: %w", err)
	}

	// Cache the validation result
	cacheValidation(licenseKey, result)

	return result, nil
}

// ServiceLicensePayload represents the JSON payload in an Ed25519-signed license.
//
// W4 plugin-claim additions (TenantID, Aud, JTI, KID, Origin) are all
// `omitempty` so they only appear in plugin-claim tokens. Self-hosted
// (Evaluation/Professional/Enterprise/Plus) tokens continue to serialize
// without these fields, preserving backward compatibility — existing
// validators don't read fields they don't know about.
type ServiceLicensePayload struct {
	LicenseID   string      `json:"id,omitempty"`           // Unique license ID
	Tier        string      `json:"tier"`
	OrgID       string      `json:"org_id"`
	ServiceName string      `json:"service_name,omitempty"`
	ServiceType string      `json:"service_type,omitempty"`
	Permissions []string    `json:"permissions,omitempty"`
	IssuedAt    string      `json:"issued_at,omitempty"` // Format: YYYYMMDD
	ExpiresAt   string      `json:"expires_at"`          // Format: YYYYMMDD
	Email       string      `json:"email,omitempty"`
	Email2      string      `json:"email2,omitempty"`
	Limits      *TierLimits `json:"limits,omitempty"`

	// W4 plugin-claim claims (per ADR-049 sections 1, 9). Only present in
	// plugin-claim tokens. Validated by agent middleware on each request.
	TenantID string `json:"tenant_id,omitempty"` // cs_<uuid> binding the token to a community-saas tenant
	Aud      string `json:"aud,omitempty"`       // expected audience: "community_saas_plugin" for plugin-claim
	JTI      string `json:"jti,omitempty"`       // unique token id (UUID v7) for revocation + audit
	KID      string `json:"kid,omitempty"`       // signing key id (e.g., "v3-2026-05-04") for rotation
	Origin   string `json:"origin,omitempty"`    // "plugin" / "self_hosted_eval" / "self_hosted_enterprise" — for cross-context check
}

// expectedAudience is the canonical audience string for plugin-claim tokens.
// Validators use this to reject tokens issued for a different context (e.g.,
// a token signed for "orchestrator_boot" must NOT be accepted by the agent
// middleware which expects "community_saas_plugin"). Per ADR-049 section 1.
const ExpectedPluginClaimAudience = "community_saas_plugin"

// expectedPluginOrigin is the canonical origin string for plugin-claim tokens.
// Tokens with origin != "plugin" must be rejected by plugin-claim validators
// (defense-in-depth alongside the audience check).
const ExpectedPluginClaimOrigin = "plugin"

// PluginClaimValidationError indicates the token failed a plugin-claim-specific
// validation step (audience, origin). Distinct error type so callers can
// distinguish "this is an Ed25519-valid token but not for our context" from
// "this token's signature doesn't verify".
type PluginClaimValidationError struct {
	Reason string
}

func (e *PluginClaimValidationError) Error() string {
	return "plugin-claim validation failed: " + e.Reason
}

// validateEd25519License validates an Ed25519-signed license key.
// Format: AXON-{BASE64URL(JSON_PAYLOAD)}.{BASE64URL(ED25519_SIGNATURE)}
func validateEd25519License(licenseKey string) (*ValidationResult, error) {
	// Strip "AXON-" prefix
	rest := licenseKey[5:]

	// Split on "." — payload.signature
	dotIdx := strings.LastIndex(rest, ".")
	if dotIdx < 1 {
		return nil, errors.New("invalid license format: missing signature separator")
	}

	payloadBase64 := rest[:dotIdx]
	signatureBase64 := rest[dotIdx+1:]

	// Decode payload
	payloadJSON, err := base64.RawURLEncoding.DecodeString(payloadBase64)
	if err != nil {
		return nil, fmt.Errorf("invalid payload encoding: %w", err)
	}

	// Parse JSON payload
	var payload ServiceLicensePayload
	if err := json.Unmarshal(payloadJSON, &payload); err != nil {
		return nil, fmt.Errorf("invalid payload JSON: %w", err)
	}

	// Decode signature
	signature, err := base64.RawURLEncoding.DecodeString(signatureBase64)
	if err != nil {
		return nil, fmt.Errorf("invalid signature encoding: %w", err)
	}

	if len(signature) != ed25519.SignatureSize {
		return nil, fmt.Errorf("invalid signature length: expected %d bytes, got %d", ed25519.SignatureSize, len(signature))
	}

	// Determine tier and select appropriate public key.
	// normalizeTier handles both legacy abbreviations (PRO, ENT, PLUS, EVALUATION)
	// and the canonical full names used in newly issued licenses.
	tier := normalizeTier(payload.Tier)
	if !verifyEd25519Signature([]byte(payloadBase64), signature, tier) {
		return nil, errors.New("invalid license signature")
	}

	// Validate tier
	switch tier {
	case TierEvaluation, TierProfessional, TierEnterprise, TierEnterprisePlus:
		// valid
	default:
		return nil, fmt.Errorf("invalid license tier: %s", tier)
	}

	// Parse expiry date
	expiry, err := time.Parse("20060102", payload.ExpiresAt)
	if err != nil {
		return nil, fmt.Errorf("invalid expiry date format: %w", err)
	}

	// Check expiry
	now := time.Now()
	daysUntilExpiry := int(expiry.Sub(now).Hours() / 24)

	result := &ValidationResult{
		Valid:           true,
		Tier:            tier,
		OrgID:           payload.OrgID,
		ExpiresAt:       expiry,
		DaysUntilExpiry: daysUntilExpiry,
		GracePeriodDays: 0,
		Features:        getFeatures(tier),
		Limits:          GetTierLimits(tier),
		ServiceName:     payload.ServiceName,
		ServiceType:     payload.ServiceType,
		Permissions:     payload.Permissions,
		Email:           payload.Email,
		LicenseID:       payload.LicenseID,
	}

	// Set max nodes based on tier
	switch tier {
	case TierEvaluation:
		result.MaxNodes = 2
	case TierProfessional:
		result.MaxNodes = 10
	case TierEnterprise:
		result.MaxNodes = 50
	case TierEnterprisePlus:
		result.MaxNodes = 9999 // Unlimited
	}

	// Check if expired
	if now.After(expiry) {
		daysExpired := int(now.Sub(expiry).Hours() / 24)

		if daysExpired <= GracePeriodDays {
			result.GracePeriodDays = GracePeriodDays - daysExpired
			result.Message = fmt.Sprintf("License expired %d days ago, %d days of grace period remaining",
				daysExpired, result.GracePeriodDays)
		} else {
			result.Valid = false
			result.Error = "LICENSE_EXPIRED"
			result.Message = fmt.Sprintf("License expired on %s (grace period ended)", expiry.Format("2006-01-02"))
			return result, nil
		}
	}

	// Valid license
	if daysUntilExpiry <= 30 {
		result.Message = fmt.Sprintf("License expires in %d days", daysUntilExpiry)
	}

	return result, nil
}

// verifyEd25519Signature verifies the Ed25519 signature of a license payload.
// Selects the appropriate public key based on the license tier.
func verifyEd25519Signature(payload, signature []byte, tier Tier) bool {
	var pubKey ed25519.PublicKey
	switch tier {
	case TierEvaluation:
		pubKey = evaluationPublicKey
	default: // Professional, Enterprise, Plus
		pubKey = enterprisePublicKey
	}
	return ed25519.Verify(pubKey, payload, signature)
}

// validateOffline validates a license key without calling the license server.
// Only Ed25519-signed format (AXON-{PAYLOAD}.{SIGNATURE}) is supported.
// Old V2 (AXON-V2-...) and V1 (AXON-TIER-...) formats are rejected.
func validateOffline(licenseKey string) (*ValidationResult, error) {
	if !strings.HasPrefix(licenseKey, "AXON-") {
		return nil, errors.New("invalid license key prefix (expected AXON-)")
	}

	// Reject old V2 format
	if strings.HasPrefix(licenseKey, "AXON-V2-") {
		return nil, errors.New("V2 license format (AXON-V2-...) is no longer supported. " +
			"Please request a new license at https://getaxonflow.com/evaluation-license")
	}

	// Check for Ed25519 format: must contain "." separator after AXON- prefix
	rest := licenseKey[5:]
	if strings.Contains(rest, ".") {
		return validateEd25519License(licenseKey)
	}

	// V1 format is deprecated
	return nil, errors.New("V1 license format (AXON-TIER-ORG-...) is no longer supported. " +
		"Please request a new license at https://getaxonflow.com/evaluation-license")
}

// getFeatures returns the features enabled for a given tier
func getFeatures(tier Tier) map[string]bool {
	features := make(map[string]bool)

	switch tier {
	case TierEvaluation:
		features["audit_logging"] = true
		features["basic_support"] = true

	case TierProfessional:
		features["multi_tenant"] = false
		features["advanced_policies"] = false
		features["sla_guarantee"] = false
		features["audit_logging"] = true
		features["basic_support"] = true

	case TierEnterprise:
		features["multi_tenant"] = true
		features["advanced_policies"] = true
		features["sla_guarantee"] = true
		features["audit_logging"] = true
		features["priority_support"] = true
		features["custom_connectors"] = true

	case TierEnterprisePlus:
		features["multi_tenant"] = true
		features["advanced_policies"] = true
		features["sla_guarantee"] = true
		features["audit_logging"] = true
		features["24x7_support"] = true
		features["custom_connectors"] = true
		features["dedicated_sa"] = true
		features["unlimited_nodes"] = true
	}

	return features
}

// Thread-safe validation cache with TTL and bounded size.
// Keys are SHA-256 hashes to avoid storing license keys in plaintext.
var (
	validationCache  = make(map[string]*cachedValidation)
	validationCacheMu sync.RWMutex
	validationCacheTTL = 5 * time.Minute
	validationCacheMaxSize = 100
)

type cachedValidation struct {
	Result   *ValidationResult
	CachedAt time.Time
}

// getCachedValidation returns a cached result if it exists and is not expired.
func getCachedValidation(licenseKey string) *ValidationResult {
	keyHash := hashLicenseKey(licenseKey)
	validationCacheMu.RLock()
	entry, ok := validationCache[keyHash]
	validationCacheMu.RUnlock()
	if !ok {
		return nil
	}
	if time.Since(entry.CachedAt) > validationCacheTTL {
		validationCacheMu.Lock()
		delete(validationCache, keyHash)
		validationCacheMu.Unlock()
		return nil
	}
	return entry.Result
}

// cacheValidation stores a validation result in cache
func cacheValidation(licenseKey string, result *ValidationResult) {
	keyHash := hashLicenseKey(licenseKey)
	validationCacheMu.Lock()
	defer validationCacheMu.Unlock()
	// Evict oldest entries if cache is full
	if len(validationCache) >= validationCacheMaxSize {
		var oldestKey string
		var oldestTime time.Time
		for k, v := range validationCache {
			if oldestKey == "" || v.CachedAt.Before(oldestTime) {
				oldestKey = k
				oldestTime = v.CachedAt
			}
		}
		delete(validationCache, oldestKey)
	}
	validationCache[keyHash] = &cachedValidation{
		Result:   result,
		CachedAt: time.Now(),
	}
}

func hashLicenseKey(key string) string {
	h := sha256.Sum256([]byte(key))
	return hex.EncodeToString(h[:])
}

// ValidateWithRetry validates a license with automatic retry on transient failures
// This is the recommended function to use at agent startup
func ValidateWithRetry(ctx context.Context, licenseKey string, maxAttempts int) (*ValidationResult, error) {
	var lastErr error

	for attempt := 1; attempt <= maxAttempts; attempt++ {
		result, err := ValidateLicense(ctx, licenseKey)
		if err == nil {
			return result, nil
		}

		lastErr = err

		// Don't retry on permanent failures
		if strings.Contains(err.Error(), "invalid license") ||
			strings.Contains(err.Error(), "expired") ||
			strings.Contains(err.Error(), "no longer supported") {
			return nil, err
		}

		// Exponential backoff for retries
		if attempt < maxAttempts {
			backoff := time.Duration(attempt*attempt) * time.Second
			select {
			case <-ctx.Done():
				return nil, ctx.Err()
			case <-time.After(backoff):
				// Continue to next attempt
			}
		}
	}

	return nil, fmt.Errorf("license validation failed after %d attempts: %w", maxAttempts, lastErr)
}

// IsEnterpriseTier checks if the AXONFLOW_LICENSE_KEY environment variable
// contains a valid Enterprise or EnterprisePlus license.
// This is the canonical way to check for Enterprise license across the codebase.
func IsEnterpriseTier(ctx context.Context) bool {
	licenseKey := os.Getenv("AXONFLOW_LICENSE_KEY")
	if licenseKey == "" {
		return false
	}
	result, err := ValidateLicense(ctx, licenseKey)
	if err != nil || result == nil || !result.Valid {
		return false
	}
	return result.Tier == TierEnterprise || result.Tier == TierEnterprisePlus
}
